;;
;;
;;
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(company-tooltip-selection ((t (:extend t :background "steelblue" :foreground "#7285b7" :inverse-video t))))
 '(doom-modeline-buffer-minor-mode ((t (:inherit mode-line :slant normal))))
 '(font-lock-function-name-face ((t (:foreground "DodgerBlue1"))))
 '(font-lock-preprocessor-face ((t (:foreground "steel blue"))))
 '(font-lock-variable-name-face ((t (:foreground "DodgerBlue1"))))
 '(git-gutter:added ((t (:background "#50fa7b"))) nil "Customized with leaf in git-gutter block")
 '(git-gutter:deleted ((t (:background "#ff79c6"))) nil "Customized with leaf in git-gutter block")
 '(git-gutter:modified ((t (:background "#f1fa8c"))) nil "Customized with leaf in git-gutter block")
 '(highlight-indent-guides-character-face ((t (:background "dimgray"))) nil "Customized with leaf in highlight-indent-guides block")
 '(highlight-indent-guides-even-face ((t (:background "dimgray"))) nil "Customized with leaf in highlight-indent-guides block")
 '(highlight-indent-guides-odd-face ((t (:background "darkgray"))) nil "Customized with leaf in highlight-indent-guides block")
 '(hl-line ((t (:underline "textBackgroundColor"))))
 '(markdown-code-face ((t (:inherit nil))))
 '(mode-line ((t (:background "medium blue" :foreground "snow" :box nil))) nil "Customized with leaf in doom-modeline block")
 '(rst-level-1 ((t (:foreground "gray10" :background "gray80" :height 1.4 :weight bold))))
 '(rst-level-1-face ((t (:foreground "LightSkyBlue"))) t)
 '(rst-level-2 ((t (:foreground "gray10" :background "gray80" :height 1.2 :weight bold))))
 '(rst-level-2-face ((t (:foreground "LightGoldenrod"))) t)
 '(rst-level-3 ((t (:background "grey15" :height 1.1))))
 '(rst-level-3-face ((t (:foreground "Cyan1"))) t)
 '(rst-level-4 ((t (:background "grey15" :height 1.1))))
 '(rst-level-4-face ((t (:foreground "chocolate1"))) t)
 '(rst-level-5 ((t (:background "grey15" :height 1.1))))
 '(rst-level-5-face ((t (:foreground "PaleGreen"))) t)
 '(rst-level-6 ((t (:background "grey15" :height 1.1))))
 '(rst-level-6-face ((t (:foreground "Aquamarine"))) t))
 ;; (rst-level-7-face ((t (:foreground "LightSteelBlue"))) t)  ;; メモ
 ;; (rst-level-8-face ((t (:foreground "LightSalmon"))) t)
(put 'narrow-to-region 'disabled nil)
;;
;;
;;
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(ac-php-debug-flag nil t)
 '(ac-php-php-executable "c:/Apps/php-7.4.22-Win32-vc15-x64/php.exe" t)
 '(all-the-icons-scale-factor 1.0)
 '(auto-revert-interval 1)
 '(calendar-day-header-array ["日" "月" "火" "水" "木" "金" "土"] t)
 '(calendar-day-name-array ["日" "月" "火" "水" "木" "金" "土"] t)
 '(calendar-month-name-array
   ["01" "02" "03" "04" "05" "06" "07" "08" "09" "10" "11" "12"] t)
 '(calendar-week-start-day 0 t)
 '(cider-auto-select-error-buffer t t)
 '(cider-repl-result-prefix ";; => " t)
 '(cider-show-error-buffer t t)
 '(column-number-mode 0)
 '(company-begin-commands '(self-insert-command))
 '(company-box-backends-colors
   '((company-yasnippet :candidate "yellow" :annotation some-face)
     (company-elisp :icon "yellow" :selected
		    (:background "orange" :foreground "black"))
     (company-dabbrev . "purple")) t)
 '(company-box-background
   '((t
      (:inherit company-tooltip :background "midnight blue"))) t)
 '(company-box-doc-enable t)
 '(company-box-icons-alist 'company-box-icons-all-the-icons)
 '(company-box-max-candidates 50)
 '(company-box-show-single-candidate t)
 '(company-echo-delay 0 t)
 '(company-idle-delay 0)
 '(company-minimum-prefix-length 1)
 '(company-quickhelp-color-foreground "black")
 '(company-selection-wrap-around t)
 '(company-tooltip-align-annotations t)
 '(company-tooltip-limit 20)
 '(completion-styles '(orderless))
 '(css-indent-offset 2 t)
 '(cua-enable-cua-keys nil)
 '(custom-enabled-themes '(sanityinc-tomorrow-blue))
 '(custom-safe-themes
   '("82d2cac368ccdec2fcc7573f24c3f79654b78bf133096f9b40c20d97ec1d8016" "4639288d273cbd3dc880992e6032f9c817f17c4a91f00f3872009a099f5b3f84" default))
 '(dashboard-items '((recents . 15) (projects . 5) (bookmarks . 5)))
 '(dired-dwim-target t)
 '(dired-isearch-filenames t t)
 '(dired-recursive-copies 'always)
 '(display-graphic-p nil t)
 '(doom-modeline-buffer-encoding t)
 '(doom-modeline-buffer-file-name-style 'truncate-with-project)
 '(doom-modeline-icon t)
 '(doom-modeline-major-mode-icon nil)
 '(doom-modeline-minor-modes t)
 '(flycheck-disabled-checkers '(javascript-jshint javascript-jscs) t)
 '(flycheck-display-errors-function 'flycheck-pos-tip-error-messages t)
 '(flycheck-php-phpcs-executable "phpcs" t)
 '(git-gutter:added-sign "+" t)
 '(git-gutter:deleted-sign "-" t)
 '(git-gutter:modified-sign "~" t)
 '(git-gutter:window-width 0 t)
 '(helm-truncate-lines t t)
 '(highlight-indent-guides-auto-enabled t t)
 '(highlight-indent-guides-character 124 t)
 '(highlight-indent-guides-method 'character t)
 '(highlight-indent-guides-responsive t t)
 '(inferior-lisp-program " run" t)
 '(js-indent-level 2 t)
 '(js2-basic-offset 2 t)
 '(line-number-mode 0)
 '(ls-lisp-dirs-first t)
 '(mark-holidays-in-calendar t t)
 '(markdown-header-scaling nil t)
 '(markdown-open-command "c:/Program Files/Typora/Typora.exe" t)
 '(markdown-use-pandoc-style-yaml-metadata t t)
 '(migemo-coding-system nil t)
 '(migemo-command "cmigemo" t)
 '(migemo-dictionary `(expand-file-name "~/.emacs.d/migemo/utf-8/migemo-dict") t)
 '(migemo-options '("-q" "--emacs") t)
 '(migemo-pattern-alist-length 1024 t)
 '(migemo-regex-dictionary nil t)
 '(migemo-use-frequent-pattern-alist t t)
 '(migemo-use-pattern-alist t t)
 '(migemo-user-dictionary nil t)
 '(nrepl-hide-special-buffers t t)
 '(nrepl-sync-request-timeout 40 t)
 '(open-junk-file-format "~/Downloads/junk/%Y-%m-%d-%H%M%S." t)
 '(orderless-matching-styles
   '(orderless-prefixes orderless-flex orderless-regexp orderless-initialism orderless-literal) t)
 '(org-adapt-indentation nil t)
 '(org-bullets-bullet-list '("" "" "" "" "" "" "") t)
 '(org-clock-clocked-in-display 'none t)
 '(org-clock-out-remove-zero-time-clocks t t)
 '(org-download-image-dir "./img" t)
 '(org-indent-indentation-per-level 0 t)
 '(org-log-done t t)
 '(org-outline-path-complete-in-steps nil t)
 '(org-refile-use-outline-path 'file t)
 '(org-return-follows-link t t)
 '(org-src-fontify-natively t t)
 '(org-startup-truncated t t)
 '(org-todo-keywords
   '((sequence "TODO(t)" "WAITING(w)" "|" "DONE(d)" "CANCELED(c)")) t)
 '(package-archives
   '(("gnu" . "https://elpa.gnu.org/packages/")
     ("melpa" . "https://melpa.org/packages/")
     ("marmalade" . "https://marmalade-repo.org/packages/")
     ("org" . "https://orgmode.org/elpa/")))
 '(package-selected-packages '(init-loader leaf leaf-keywords pastels-on-dark-theme))
 '(php-manual-url 'ja t)
 '(php-mode-coding-style 'psr2 t)
 '(projectile-enable-caching t)
 '(projectile-enable-idle-timer nil)
 '(recentf-max-saved-items 200)
 '(recentf-save-file "c:/Users/masao/.emacs.d/recentf")
 '(regexp-opt nil t)
 '(safe-local-variable-values
   '((php-project-root . auto)
     (phpstan-executable . "phpstan")
     (phpstan-level . 7)
     (phpstan-config-file root . ".phpstan/phpstan-custom.neon")
     (phpstan-working-dir root . ".phpstan")
     (phpstan-executable . "C:/Apps/phpstan/vendor/bin/phpstan.bat")
     (php-project-root . git)
     (phpstan-memory-limit . "1G")
     (phpstan-executable quote docker)
     (cider-ns-refresh-after-fn . "integrant.repl/resume")
     (cider-ns-refresh-before-fn . "integrant.repl/suspend")
     (checkdoc-package-keywords-flag)
     (cider-ns-refresh-after-fn . "reloaded.repl/resume")
     (cider-ns-refresh-before-fn . "reloaded.repl/suspend")
     (cider-default-cljs-repl . "(do (user/go) (user/cljs-repl))")
     (cider-cljs-lein-repl . "(do (user/go) (user/cljs-repl))")
     (cider-cljs-lein-repl . "(do (dev) (go) (cljs-repl))")
     (cider-refresh-after-fn . "reloaded.repl/resume")
     (cider-refresh-before-fn . "reloaded.repl/suspend")
     (emacs-lisp-docstring-fill-column . 75)))
 '(scss-compile-at-save nil t)
 '(shell-command-switch "-c" t)
 '(sql-product 'postgres t)
 '(swiper-include-line-number-in-search t)
 '(tide-format-options '(:indentSize 2 :tabSize 2))
 '(typescript-indent-level 2)
 '(vertico-cycle t)
 '(w32-symlinks-handle-shortcuts t)
 '(warning-suppress-log-types '((leaf) (straight)))
 '(warning-suppress-types '((straight)))
 '(web-mode-code-indent-offset 2)
 '(web-mode-markup-indent-offset 2)
 '(whitespace-display-mappings '((space-mark 12288 [9633]) (tab-mark 9 [187 9])))
 '(whitespace-space-regexp "\\(　+\\)")
 '(whitespace-style
   '(face tabs tab-mark spaces space-mark trailing space-before-tab space-after-tab::space))
 '(whitespace-style-with-tab
   '(face tabs tab-mark spaces space-mark trailing space-before-tab space-after-tab::space) t)
 '(whitespace-style-without-tab
   '(face spaces space-mark trailing space-before-tab space-after-tab::space) t)
 '(yas-new-snippet-default
   "# -*- mode: snippet -*-
# name: $1
# key: ${2:${1:$(yas--key-from-desc yas-text)}}
# expand-env: ((yas/indent-line 'fixed) (yas/wrap-around-region 'nil))
# --
$0"))
