;;
;;
;;
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(company-box-background ((t (:inherit company-tooltip :background "midnight blue"))))
 '(company-preview ((t (:foreground "darkgray" :underline t))))
 '(company-preview-common ((t (:inherit company-preview))))
 '(company-scrollbar-bg ((t (:background "gray40"))))
 '(company-scrollbar-fg ((t (:background "orange"))))
 '(company-tooltip ((t (:background "lightgray" :foreground "black"))))
 '(company-tooltip-common ((((type x)) (:inherit company-tooltip :weight bold)) (t (:inherit company-tooltip))))
 '(company-tooltip-common-selection ((((type x)) (:inherit company-tooltip-selection :weight bold)) (t (:inherit company-tooltip-selection))))
 '(company-tooltip-selection ((t (:background "steelblue" :foreground "white"))))
 '(doom-modeline-buffer-minor-mode ((t (:inherit mode-line :slant normal))))
 '(font-lock-function-name-face ((t (:foreground "DodgerBlue1"))))
 '(font-lock-preprocessor-face ((t (:foreground "steel blue"))))
 '(font-lock-variable-name-face ((t (:foreground "DodgerBlue1"))))
 '(git-gutter:added ((t (:background "#50fa7b"))) nil "Customized with leaf in git-gutter block")
 '(git-gutter:deleted ((t (:background "#ff79c6"))) nil "Customized with leaf in git-gutter block")
 '(git-gutter:modified ((t (:background "#f1fa8c"))) nil "Customized with leaf in git-gutter block")
 '(hl-line ((t (:underline "textBackgroundColor"))))
 '(mode-line ((t (:background "medium blue" :foreground "snow" :box nil))) nil "Customized with leaf in doom-modeline block")
 '(rst-level-1-face ((t (:foreground "LightSkyBlue"))) t)
 '(rst-level-2-face ((t (:foreground "LightGoldenrod"))) t)
 '(rst-level-3-face ((t (:foreground "Cyan1"))) t)
 '(rst-level-4-face ((t (:foreground "chocolate1"))) t)
 '(rst-level-5-face ((t (:foreground "PaleGreen"))) t)
 '(rst-level-6-face ((t (:foreground "Aquamarine"))) t))
 ;; (rst-level-7-face ((t (:foreground "LightSteelBlue"))) t)  ;; メモ
 ;; (rst-level-8-face ((t (:foreground "LightSalmon"))) t)
(put 'narrow-to-region 'disabled nil)
;;
;;
;;
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(all-the-icons-scale-factor 1.0)
 '(cider-auto-select-error-buffer t t)
 '(cider-repl-result-prefix ";; => " t)
 '(cider-show-error-buffer t t)
 '(column-number-mode 0)
 '(company-begin-commands '(self-insert-command))
 '(company-box-backends-colors
   '((company-yasnippet :candidate "yellow" :annotation some-face)
     (company-elisp :icon "yellow" :selected
		    (:background "orange" :foreground "black"))
     (company-dabbrev . "purple")) t)
 '(company-box-background
   '((t
      (:inherit company-tooltip :background "midnight blue"))) t)
 '(company-box-doc-enable t)
 '(company-box-icons-alist 'company-box-icons-all-the-icons)
 '(company-box-max-candidates 50)
 '(company-box-show-single-candidate t)
 '(company-echo-delay 0 t)
 '(company-idle-delay 0)
 '(company-minimum-prefix-length 1)
 '(company-quickhelp-color-foreground "black")
 '(company-selection-wrap-around t)
 '(company-tooltip-align-annotations t)
 '(company-tooltip-limit 20)
 '(counsel-find-file-ignore-regexp nil)
 '(css-indent-offset 2 t)
 '(cua-enable-cua-keys nil)
 '(custom-safe-themes
   '("4639288d273cbd3dc880992e6032f9c817f17c4a91f00f3872009a099f5b3f84" default))
 '(dashboard-items '((recents . 15) (projects . 5) (bookmarks . 5)))
 '(dired-dwim-target t)
 '(dired-isearch-filenames t)
 '(dired-recursive-copies 'always)
 '(doom-modeline-buffer-file-name-style 'truncate-with-project)
 '(doom-modeline-icon t)
 '(doom-modeline-major-mode-icon nil)
 '(doom-modeline-minor-modes nil)
 '(flycheck-disabled-checkers '(javascript-jshint javascript-jscs))
 '(flycheck-display-errors-function #'flycheck-pos-tip-error-messages)
 '(helm-truncate-lines t t)
 '(inferior-lisp-program "/usr/local/bin/ros run" t)
 '(ivy-count-format "(%d/%d) ")
 '(ivy-extra-directories '("../" "./"))
 '(ivy-format-functions-alist '((t . ivy-format-function-arrow)))
 '(ivy-height 20)
 '(ivy-re-builders-alist '((t . ivy--regex-plus)) t)
 '(ivy-use-virtual-buffers t)
 '(ivy-wrap t)
 '(js-indent-level 2)
 '(js2-basic-offset 2)
 '(line-number-mode 0)
 '(migemo-coding-system nil t)
 '(migemo-command "cmigemo" t)
 '(migemo-dictionary `(expand-file-name "~/.emacs.d/migemo/utf-8/migemo-dict") t)
 '(migemo-options '("-q" "--emacs") t)
 '(migemo-pattern-alist-length 1024 t)
 '(migemo-regex-dictionary nil t)
 '(migemo-use-frequent-pattern-alist t t)
 '(migemo-use-pattern-alist t t)
 '(migemo-user-dictionary nil t)
 '(nrepl-hide-special-buffers t t)
 '(nrepl-sync-request-timeout 40 t)
 '(open-junk-file-format "~/Downloads/junk/%Y-%m-%d-%H%M%S." t)
 '(org-adapt-indentation nil t)
 '(org-bullets-bullet-list '("" "" "" "" "" "" "") t)
 '(org-clock-clocked-in-display 'none t)
 '(org-clock-out-remove-zero-time-clocks t t)
 '(org-download-image-dir "./img" t)
 '(org-indent-indentation-per-level 0 t)
 '(org-log-done t t)
 '(org-outline-path-complete-in-steps nil t)
 '(org-refile-use-outline-path 'file t)
 '(org-return-follows-link t t)
 '(org-src-fontify-natively t t)
 '(org-startup-truncated t t)
 '(org-todo-keywords
   '((sequence "TODO(t)" "WAITING(w)" "|" "DONE(d)" "CANCELED(c)")) t)
 '(package-selected-packages '(init-loader leaf leaf-keywords pastels-on-dark-theme))
 '(projectile-completion-system 'ivy)
 '(projectile-enable-caching t)
 '(projectile-enable-idle-timer nil)
 '(recentf-max-saved-items 200)
 '(recentf-save-file "/Users/masao/.emacs.d/recentf")
 '(regexp-opt nil t)
 '(safe-local-variable-values
   '((php-project-root . auto)
     (phpstan-executable . "phpstan")
     (phpstan-level . 7)
     (phpstan-config-file root . ".phpstan/phpstan-custom.neon")
     (phpstan-working-dir root . ".phpstan")
     (phpstan-executable . "C:/Apps/phpstan/vendor/bin/phpstan.bat")
     (php-project-root . git)
     (phpstan-memory-limit . "1G")
     (phpstan-executable quote docker)
     (cider-ns-refresh-after-fn . "integrant.repl/resume")
     (cider-ns-refresh-before-fn . "integrant.repl/suspend")
     (checkdoc-package-keywords-flag)
     (cider-ns-refresh-after-fn . "reloaded.repl/resume")
     (cider-ns-refresh-before-fn . "reloaded.repl/suspend")
     (cider-default-cljs-repl . "(do (user/go) (user/cljs-repl))")
     (cider-cljs-lein-repl . "(do (user/go) (user/cljs-repl))")
     (cider-cljs-lein-repl . "(do (dev) (go) (cljs-repl))")
     (cider-refresh-after-fn . "reloaded.repl/resume")
     (cider-refresh-before-fn . "reloaded.repl/suspend")
     (emacs-lisp-docstring-fill-column . 75)))
 '(scss-compile-at-save nil t)
 '(shell-command-switch "-c" t)
 '(sql-product 'postgres t)
 '(swiper-include-line-number-in-search t)
 '(tide-format-options '(:indentSize 2 :tabSize 2))
 '(typescript-indent-level 2)
 '(w32-symlinks-handle-shortcuts t)
 '(web-mode-code-indent-offset 2)
 '(web-mode-markup-indent-offset 2)
 '(yas-new-snippet-default
   "# -*- mode: snippet -*-
# name: $1
# key: ${2:${1:$(yas--key-from-desc yas-text)}}
# expand-env: ((yas/indent-line 'fixed) (yas/wrap-around-region 'nil))
# --
$0"))
