#+TITLE: Nerd Font と starship の記号
#+STARTUP: showall

starship のプロンプトに出ている記号を選ぶための一覧。
グリフの有無は =Symbols Nerd Font Mono= に実際に問い合わせて作った。
作り直すときは =M-x my:nerd-font-sample-generate= (GUI で)。

コードチャートは 16 個ずつ並べてあり、行頭がその行の先頭の
コードポイント。左から数えれば任意の 1 個の綴りが分かる。
グリフが無いところは =·= で埋めてある。
starship.toml には記号をそのまま貼ればよい (=\uXXXX= の
エスケープは要らない)。

**桁は揃わない。** アイコンは 15px、半角は 8px なので、
16 個並べても列は一致しない。数えるための並びであって、
表ではない。

* starship で使っている記号

** いまの設定 (~/.config/starship.toml)
format                               
os.symbols.Windows                   󰍲
os.symbols.Ubuntu                    󰕈
os.symbols.SUSE                      
os.symbols.Raspbian                  󰐿
os.symbols.Mint                      󰣭
os.symbols.Macos                     󰀵
os.symbols.Manjaro                   
os.symbols.Linux                     󰌽
os.symbols.Gentoo                    󰣨
os.symbols.Fedora                    󰣛
os.symbols.Alpine                    
os.symbols.Amazon                    
os.symbols.Android                   
os.symbols.AOSC                      
os.symbols.Arch                      󰣇
os.symbols.Artix                     󰣇
os.symbols.EndeavourOS               
os.symbols.CentOS                    
os.symbols.Debian                    󰣚
os.symbols.Redhat                    󱄛
os.symbols.RedHatEnterprise          󱄛
os.symbols.Pop                       
directory.truncation_symbol          …
directory.substitutions."Documents"  󰈙
directory.substitutions."Downloads"  
directory.substitutions."Music"      󰝚
directory.substitutions."Pictures"   
directory.substitutions."Developer"  󰲋
git_branch.symbol                    
nodejs.symbol                        
c.symbol                             
cpp.symbol                           
rust.symbol                          
golang.symbol                        
php.symbol                           
java.symbol                          
kotlin.symbol                        
haskell.symbol                       
python.symbol                        
docker_context.symbol                
time.format                          
character.success_symbol             
character.error_symbol               
character.vimcmd_symbol              
character.vimcmd_replace_one_symbol  
character.vimcmd_replace_symbol      
character.vimcmd_visual_symbol       

** starship の既定値 (starship 1.26.0)

=starship print-config= の出力。設定で上書きしていない
モジュールはこの記号が出る。

format                               
continuation_prompt                  ∙
aws.symbol                           ☁
azure.symbol                         󰠅
battery.full_symbol                  󰁹
battery.charging_symbol              󰂄
battery.discharging_symbol           󰂃
battery.unknown_symbol               󰂑
battery.empty_symbol                 󰂎
buf.symbol                           🐃
bun.symbol                           🥟
c.symbol                             
character.success_symbol             
character.error_symbol               
character.vimcmd_symbol              
character.vimcmd_visual_symbol       
character.vimcmd_replace_symbol      
character.vimcmd_replace_one_symbol  
claude_context.gauge_full_symbol     █
claude_context.gauge_partial_symbol  ▒
claude_context.gauge_empty_symbol    ░
claude_cost.symbol                   💰
claude_model.symbol                  🤖
cmake.symbol                         △
cobol.symbol                         ⚙
conda.symbol                         🅒
container.symbol                     ⬢
cpp.symbol                           
crystal.symbol                       🔮
daml.symbol                          Λ
dart.symbol                          🎯
deno.symbol                          🦕
directory.read_only                  🔒
directory.truncation_symbol          …
directory.substitutions.Documents    󰈙
directory.substitutions.Downloads    
directory.substitutions.Music        󰝚
directory.substitutions.Pictures     
directory.substitutions.Developer    󰲋
docker_context.symbol                
dotnet.format                        🎯
elixir.symbol                        💧
elm.symbol                           🌳
erlang.symbol                        
fennel.symbol                        🧅
fortran.symbol                       🅵
fossil_branch.symbol                 
fossil_branch.truncation_symbol      …
gcloud.symbol                        ☁
git_branch.symbol                    
git_branch.truncation_symbol         …
git_commit.tag_symbol                🏷
git_status.ahead                     ⇡
git_status.behind                    ⇣
git_status.diverged                  ⇕
git_status.deleted                   ✘
git_status.renamed                   »
gleam.symbol                         ⭐
golang.symbol                        
gradle.symbol                        🅶
guix_shell.symbol                    🐃
haskell.symbol                       
haxe.symbol                          ⌘
helm.symbol                          ⎈
hg_branch.symbol                     
hg_branch.truncation_symbol          …
hostname.ssh_symbol                  🌐
java.symbol                          
jobs.symbol                          ✦
julia.symbol                         ஃ
kotlin.symbol                        
kubernetes.symbol                    ☸
lua.symbol                           🌙
maven.symbol                         🅼
memory_usage.symbol                  🐏
meson.truncation_symbol              …
meson.symbol                         ⬢
mojo.symbol                          🔥
nats.symbol                          ✉
netns.symbol                         🛜
nim.symbol                           👑
nix_shell.symbol                     ❄
nodejs.symbol                        
ocaml.symbol                         🐫
odin.symbol                          Ø
opa.symbol                           🪖
openstack.symbol                     ☁
os.symbols.Windows                   󰍲
os.symbols.Ubuntu                    󰕈
os.symbols.SUSE                      
os.symbols.Raspbian                  󰐿
os.symbols.Mint                      󰣭
os.symbols.Macos                     󰀵
os.symbols.Manjaro                   
os.symbols.Linux                     󰌽
os.symbols.Gentoo                    󰣨
os.symbols.Fedora                    󰣛
os.symbols.Alpine                    
os.symbols.Amazon                    
os.symbols.Android                   
os.symbols.AOSC                      
os.symbols.Arch                      󰣇
os.symbols.Artix                     󰣇
os.symbols.EndeavourOS               
os.symbols.CentOS                    
os.symbols.Debian                    󰣚
os.symbols.Redhat                    󱄛
os.symbols.RedHatEnterprise          󱄛
os.symbols.Pop                       
package.symbol                       📦
perl.symbol                          🐪
php.symbol                           
pijul_channel.symbol                 
pijul_channel.truncation_symbol      …
pixi.symbol                          🧚
pulumi.symbol                        
python.symbol                        
quarto.symbol                        ⨁
raku.symbol                          🦋
red.symbol                           🔺
rlang.symbol                         📐
ruby.symbol                          💎
rust.symbol                          
scala.symbol                         🆂
shlvl.symbol                         ↕
spack.symbol                         🅢
status.symbol                        ❌
status.not_executable_symbol         🚫
status.not_found_symbol              🔍
status.sigint_symbol                 🧱
status.signal_symbol                 ⚡
sudo.symbol                          🧙
swift.symbol                         🐦
terraform.symbol                     💠
time.format                          
vagrant.symbol                       ⍱
xmake.symbol                         △
zig.symbol                           ↯

* Nerd Fonts の一覧

** Pomicons (E000–E00A)
E000               · · · · ·

** Powerline (Symbols + Extra) (E0A0–E0D7)
E0A0        · · · · · · · · · · · ·
E0B0                   
E0C0             ·  ·    
E0D0       ·  ·   · · · · · · · ·

** Font Awesome Extension (E200–E2A9)
E200                   
E210                   
E220                   
E230                   
E240                   
E250                   
E260                   
E270                   
E280                   
E290                   
E2A0              · · · · · ·

** Weather (E300–E3E3)
E300                   
E310                   
E320                   
E330                   
E340                   
E350                   
E360                   
E370                   
E380                   
E390                   
E3A0                   
E3B0                   
E3C0                   
E3D0                   
E3E0        · · · · · · · · · · · ·

** Seti-UI + Custom (E5FA–E6BB)
E5F0    · · · · · · · · · ·      
E600                   
E610                   
E620                   
E630                   
E640                   
E650                   
E660                   
E670                   
E680                   
E690                   
E6A0                   
E6B0                · · · ·

** Devicons (E700–E958)
E700                   
E710                   
E720                   
E730                   
E740                   
E750                   
E760                   
E770                   
E780                   
E790                   
E7A0                   
E7B0                   
E7C0                   
E7D0                   
E7E0                   
E7F0                   
E800                   
E810                   
E820                   
E830                   
E840                   
E850                   
E860                   
E870                   
E880                   
E890                   
E8A0                   
E8B0                   
E8C0                   
E8D0                   
E8E0                   
E8F0                   
E900                   
E910                   
E920                   
E930                   
E940                   
E950             · · · · · · ·

** Codicons (EA60–EC84)
EA60                   
EA70                   
EA80             ·    · · 
EA90                   
EAA0                   
EAB0                   
EAC0            ·  · ·    
EAD0                   
EAE0                   
EAF0                   
EB00              ·     
EB10                   
EB20                   
EB30                   
EB40                   ·
EB50                   
EB60                   
EB70                   
EB80                   
EB90                   
EBA0                   
EBB0                   
EBC0                   
EBD0                   
EBE0                   
EBF0                   
EC00                   
EC10                   
EC20                   
EC30                   
EC40                   
EC50                   ·
EC60                   
EC70                   
EC80         · · · · · · · · · · ·

** Font Awesome (ED00–EFCF)
ED00                   
ED10                   
ED20                   
ED30                   
ED40                   
ED50                   
ED60                   
ED70                   
ED80                   
ED90                   
EDA0                   
EDB0                   
EDC0                   
EDD0                   
EDE0                   
EDF0                   
EE00                   
EE10                   
EE20                   
EE30                   
EE40                   
EE50                   
EE60                   
EE70                   
EE80                   
EE90                   
EEA0                   
EEB0                   
EEC0                   
EED0                   
EEE0                   
EEF0                   
EF00                   
EF10                   
EF20                   
EF30                   
EF40                   
EF50                   
EF60                   
EF70                   
EF80                   
EF90                   
EFA0                   
EFB0                   
EFC0                   

** Font Awesome (v2 の旧位置) (F000–F2FF)
F000                   
F010                   
F020                   
F030                   
F040                   
F050                   
F060                   
F070                   
F080                   
F090                   
F0A0                   
F0B0                   
F0C0                   
F0D0                   
F0E0                   
F0F0                   
F100                   
F110                   
F120                   
F130                   
F140                   
F150                   
F160                   
F170                   
F180                   
F190                   
F1A0                   
F1B0                   
F1C0                   
F1D0                   
F1E0                   
F1F0                   
F200                   
F210                   
F220                   
F230                   
F240                   
F250                   
F260                   
F270                   
F280                   
F290                   
F2A0                   
F2B0                   
F2C0                   
F2D0                   
F2E0                   
F2F0                   

** Font Logos (OS・ディストリ) (F300–F385)
F300                   
F310                   
F320                   
F330                   
F340                   
F350                   
F360                   
F370                   
F380          · · · · · · · · · ·

** Octicons (F400–F533)
F400                   
F410                   
F420                   
F430                   
F440                   
F450                   
F460                   
F470                   
F480                   
F490                   
F4A0                   
F4B0                   
F4C0                   
F4D0                   
F4E0                   
F4F0                   
F500                   
F510                   
F520                   
F530        · · · · · · · · · · · ·

** Material Design Icons (F0001–F1AF0)

*** F0001–F03FF
F0000   · 󰀁 󰀂 󰀃 󰀄 󰀅 󰀆 󰀇 󰀈 󰀉 󰀊 󰀋 󰀌 󰀍 󰀎 󰀏
F0010   󰀐 󰀑 󰀒 󰀓 󰀔 󰀕 󰀖 󰀗 󰀘 󰀙 󰀚 󰀛 󰀜 󰀝 󰀞 󰀟
F0020   󰀠 󰀡 󰀢 󰀣 󰀤 󰀥 󰀦 󰀧 󰀨 󰀩 󰀪 󰀫 󰀬 󰀭 󰀮 󰀯
F0030   󰀰 󰀱 󰀲 󰀳 󰀴 󰀵 󰀶 󰀷 󰀸 󰀹 󰀺 󰀻 󰀼 󰀽 󰀾 󰀿
F0040   󰁀 󰁁 󰁂 󰁃 󰁄 󰁅 󰁆 󰁇 󰁈 󰁉 󰁊 󰁋 󰁌 󰁍 󰁎 󰁏
F0050   󰁐 󰁑 󰁒 󰁓 󰁔 󰁕 󰁖 󰁗 󰁘 󰁙 󰁚 󰁛 󰁜 󰁝 󰁞 󰁟
F0060   󰁠 󰁡 󰁢 󰁣 󰁤 󰁥 󰁦 󰁧 󰁨 󰁩 󰁪 󰁫 󰁬 󰁭 󰁮 󰁯
F0070   󰁰 󰁱 󰁲 󰁳 󰁴 󰁵 󰁶 󰁷 󰁸 󰁹 󰁺 󰁻 󰁼 󰁽 󰁾 󰁿
F0080   󰂀 󰂁 󰂂 󰂃 󰂄 󰂅 󰂆 󰂇 󰂈 󰂉 󰂊 󰂋 󰂌 󰂍 󰂎 󰂏
F0090   󰂐 󰂑 󰂒 󰂓 󰂔 󰂕 󰂖 󰂗 󰂘 󰂙 󰂚 󰂛 󰂜 󰂝 󰂞 󰂟
F00A0   󰂠 󰂡 󰂢 󰂣 󰂤 󰂥 󰂦 󰂧 󰂨 󰂩 󰂪 󰂫 󰂬 󰂭 󰂮 󰂯
F00B0   󰂰 󰂱 󰂲 󰂳 󰂴 󰂵 󰂶 󰂷 󰂸 󰂹 󰂺 󰂻 󰂼 󰂽 󰂾 󰂿
F00C0   󰃀 󰃁 󰃂 󰃃 󰃄 󰃅 󰃆 󰃇 󰃈 󰃉 󰃊 󰃋 󰃌 󰃍 󰃎 󰃏
F00D0   󰃐 󰃑 󰃒 󰃓 󰃔 󰃕 󰃖 󰃗 󰃘 󰃙 󰃚 󰃛 󰃜 󰃝 󰃞 󰃟
F00E0   󰃠 󰃡 󰃢 󰃣 󰃤 󰃥 󰃦 󰃧 󰃨 󰃩 󰃪 󰃫 󰃬 󰃭 󰃮 󰃯
F00F0   󰃰 󰃱 󰃲 󰃳 󰃴 󰃵 󰃶 󰃷 󰃸 󰃹 󰃺 󰃻 󰃼 󰃽 󰃾 󰃿
F0100   󰄀 󰄁 󰄂 󰄃 󰄄 󰄅 󰄆 󰄇 󰄈 󰄉 󰄊 󰄋 󰄌 󰄍 󰄎 󰄏
F0110   󰄐 󰄑 󰄒 󰄓 󰄔 󰄕 󰄖 󰄗 󰄘 󰄙 󰄚 󰄛 󰄜 󰄝 󰄞 󰄟
F0120   󰄠 󰄡 󰄢 󰄣 󰄤 󰄥 󰄦 󰄧 󰄨 󰄩 󰄪 󰄫 󰄬 󰄭 󰄮 󰄯
F0130   󰄰 󰄱 󰄲 󰄳 󰄴 󰄵 󰄶 󰄷 󰄸 󰄹 󰄺 󰄻 󰄼 󰄽 󰄾 󰄿
F0140   󰅀 󰅁 󰅂 󰅃 󰅄 󰅅 󰅆 󰅇 󰅈 󰅉 󰅊 󰅋 󰅌 󰅍 󰅎 󰅏
F0150   󰅐 󰅑 󰅒 󰅓 󰅔 󰅕 󰅖 󰅗 󰅘 󰅙 󰅚 󰅛 󰅜 󰅝 󰅞 󰅟
F0160   󰅠 󰅡 󰅢 󰅣 󰅤 󰅥 󰅦 󰅧 󰅨 󰅩 󰅪 󰅫 󰅬 󰅭 󰅮 󰅯
F0170   󰅰 󰅱 󰅲 󰅳 󰅴 󰅵 󰅶 󰅷 󰅸 󰅹 󰅺 󰅻 󰅼 󰅽 󰅾 󰅿
F0180   󰆀 󰆁 󰆂 󰆃 󰆄 󰆅 󰆆 󰆇 󰆈 󰆉 󰆊 󰆋 󰆌 󰆍 󰆎 󰆏
F0190   󰆐 󰆑 󰆒 󰆓 󰆔 󰆕 󰆖 󰆗 󰆘 󰆙 󰆚 󰆛 󰆜 󰆝 󰆞 󰆟
F01A0   󰆠 󰆡 󰆢 󰆣 󰆤 󰆥 󰆦 󰆧 󰆨 󰆩 󰆪 󰆫 󰆬 󰆭 󰆮 󰆯
F01B0   󰆰 󰆱 󰆲 󰆳 󰆴 󰆵 󰆶 󰆷 󰆸 󰆹 󰆺 󰆻 󰆼 󰆽 󰆾 󰆿
F01C0   󰇀 󰇁 󰇂 󰇃 󰇄 󰇅 󰇆 󰇇 󰇈 󰇉 󰇊 󰇋 󰇌 󰇍 󰇎 󰇏
F01D0   󰇐 󰇑 󰇒 󰇓 󰇔 󰇕 󰇖 󰇗 󰇘 󰇙 󰇚 󰇛 󰇜 󰇝 󰇞 󰇟
F01E0   󰇠 󰇡 󰇢 󰇣 󰇤 󰇥 󰇦 󰇧 󰇨 󰇩 󰇪 󰇫 󰇬 󰇭 󰇮 󰇯
F01F0   󰇰 󰇱 󰇲 󰇳 󰇴 󰇵 󰇶 󰇷 󰇸 󰇹 󰇺 󰇻 󰇼 󰇽 󰇾 󰇿
F0200   󰈀 󰈁 󰈂 󰈃 󰈄 󰈅 󰈆 󰈇 󰈈 󰈉 󰈊 󰈋 󰈌 󰈍 󰈎 󰈏
F0210   󰈐 󰈑 󰈒 󰈓 󰈔 󰈕 󰈖 󰈗 󰈘 󰈙 󰈚 󰈛 󰈜 󰈝 󰈞 󰈟
F0220   󰈠 󰈡 󰈢 󰈣 󰈤 󰈥 󰈦 󰈧 󰈨 󰈩 󰈪 󰈫 󰈬 󰈭 󰈮 󰈯
F0230   󰈰 󰈱 󰈲 󰈳 󰈴 󰈵 󰈶 󰈷 󰈸 󰈹 󰈺 󰈻 󰈼 󰈽 󰈾 󰈿
F0240   󰉀 󰉁 󰉂 󰉃 󰉄 󰉅 󰉆 󰉇 󰉈 󰉉 󰉊 󰉋 󰉌 󰉍 󰉎 󰉏
F0250   󰉐 󰉑 󰉒 󰉓 󰉔 󰉕 󰉖 󰉗 󰉘 󰉙 󰉚 󰉛 󰉜 󰉝 󰉞 󰉟
F0260   󰉠 󰉡 󰉢 󰉣 󰉤 󰉥 󰉦 󰉧 󰉨 󰉩 󰉪 󰉫 󰉬 󰉭 󰉮 󰉯
F0270   󰉰 󰉱 󰉲 󰉳 󰉴 󰉵 󰉶 󰉷 󰉸 󰉹 󰉺 󰉻 󰉼 󰉽 󰉾 󰉿
F0280   󰊀 󰊁 󰊂 󰊃 󰊄 󰊅 󰊆 󰊇 󰊈 󰊉 󰊊 󰊋 󰊌 󰊍 󰊎 󰊏
F0290   󰊐 󰊑 󰊒 󰊓 󰊔 󰊕 󰊖 󰊗 󰊘 󰊙 󰊚 󰊛 󰊜 󰊝 󰊞 󰊟
F02A0   󰊠 󰊡 󰊢 󰊣 󰊤 󰊥 󰊦 󰊧 󰊨 󰊩 󰊪 󰊫 󰊬 󰊭 󰊮 󰊯
F02B0   󰊰 󰊱 󰊲 󰊳 󰊴 󰊵 󰊶 󰊷 󰊸 󰊹 󰊺 󰊻 󰊼 󰊽 󰊾 󰊿
F02C0   󰋀 󰋁 󰋂 󰋃 󰋄 󰋅 󰋆 󰋇 󰋈 󰋉 󰋊 󰋋 󰋌 󰋍 󰋎 󰋏
F02D0   󰋐 󰋑 󰋒 󰋓 󰋔 󰋕 󰋖 󰋗 󰋘 󰋙 󰋚 󰋛 󰋜 󰋝 󰋞 󰋟
F02E0   󰋠 󰋡 󰋢 󰋣 󰋤 󰋥 󰋦 󰋧 󰋨 󰋩 󰋪 󰋫 󰋬 󰋭 󰋮 󰋯
F02F0   󰋰 󰋱 󰋲 󰋳 󰋴 󰋵 󰋶 󰋷 󰋸 󰋹 󰋺 󰋻 󰋼 󰋽 󰋾 󰋿
F0300   󰌀 󰌁 󰌂 󰌃 󰌄 󰌅 󰌆 󰌇 󰌈 󰌉 󰌊 󰌋 󰌌 󰌍 󰌎 󰌏
F0310   󰌐 󰌑 󰌒 󰌓 󰌔 󰌕 󰌖 󰌗 󰌘 󰌙 󰌚 󰌛 󰌜 󰌝 󰌞 󰌟
F0320   󰌠 󰌡 󰌢 󰌣 󰌤 󰌥 󰌦 󰌧 󰌨 󰌩 󰌪 󰌫 󰌬 󰌭 󰌮 󰌯
F0330   󰌰 󰌱 󰌲 󰌳 󰌴 󰌵 󰌶 󰌷 󰌸 󰌹 󰌺 󰌻 󰌼 󰌽 󰌾 󰌿
F0340   󰍀 󰍁 󰍂 󰍃 󰍄 󰍅 󰍆 󰍇 󰍈 󰍉 󰍊 󰍋 󰍌 󰍍 󰍎 󰍏
F0350   󰍐 󰍑 󰍒 󰍓 󰍔 󰍕 󰍖 󰍗 󰍘 󰍙 󰍚 󰍛 󰍜 󰍝 󰍞 󰍟
F0360   󰍠 󰍡 󰍢 󰍣 󰍤 󰍥 󰍦 󰍧 󰍨 󰍩 󰍪 󰍫 󰍬 󰍭 󰍮 󰍯
F0370   󰍰 󰍱 󰍲 󰍳 󰍴 󰍵 󰍶 󰍷 󰍸 󰍹 󰍺 󰍻 󰍼 󰍽 󰍾 󰍿
F0380   󰎀 󰎁 󰎂 󰎃 󰎄 󰎅 󰎆 󰎇 󰎈 󰎉 󰎊 󰎋 󰎌 󰎍 󰎎 󰎏
F0390   󰎐 󰎑 󰎒 󰎓 󰎔 󰎕 󰎖 󰎗 󰎘 󰎙 󰎚 󰎛 󰎜 󰎝 󰎞 󰎟
F03A0   󰎠 󰎡 󰎢 󰎣 󰎤 󰎥 󰎦 󰎧 󰎨 󰎩 󰎪 󰎫 󰎬 󰎭 󰎮 󰎯
F03B0   󰎰 󰎱 󰎲 󰎳 󰎴 󰎵 󰎶 󰎷 󰎸 󰎹 󰎺 󰎻 󰎼 󰎽 󰎾 󰎿
F03C0   󰏀 󰏁 󰏂 󰏃 󰏄 󰏅 󰏆 󰏇 󰏈 󰏉 󰏊 󰏋 󰏌 󰏍 󰏎 󰏏
F03D0   󰏐 󰏑 󰏒 󰏓 󰏔 󰏕 󰏖 󰏗 󰏘 󰏙 󰏚 󰏛 󰏜 󰏝 󰏞 󰏟
F03E0   󰏠 󰏡 󰏢 󰏣 󰏤 󰏥 󰏦 󰏧 󰏨 󰏩 󰏪 󰏫 󰏬 󰏭 󰏮 󰏯
F03F0   󰏰 󰏱 󰏲 󰏳 󰏴 󰏵 󰏶 󰏷 󰏸 󰏹 󰏺 󰏻 󰏼 󰏽 󰏾 󰏿

*** F0400–F07FF
F0400   󰐀 󰐁 󰐂 󰐃 󰐄 󰐅 󰐆 󰐇 󰐈 󰐉 󰐊 󰐋 󰐌 󰐍 󰐎 󰐏
F0410   󰐐 󰐑 󰐒 󰐓 󰐔 󰐕 󰐖 󰐗 󰐘 󰐙 󰐚 󰐛 󰐜 󰐝 󰐞 󰐟
F0420   󰐠 󰐡 󰐢 󰐣 󰐤 󰐥 󰐦 󰐧 󰐨 󰐩 󰐪 󰐫 󰐬 󰐭 󰐮 󰐯
F0430   󰐰 󰐱 󰐲 󰐳 󰐴 󰐵 󰐶 󰐷 󰐸 󰐹 󰐺 󰐻 󰐼 󰐽 󰐾 󰐿
F0440   󰑀 󰑁 󰑂 󰑃 󰑄 󰑅 󰑆 󰑇 󰑈 󰑉 󰑊 󰑋 󰑌 󰑍 󰑎 󰑏
F0450   󰑐 󰑑 󰑒 󰑓 󰑔 󰑕 󰑖 󰑗 󰑘 󰑙 󰑚 󰑛 󰑜 󰑝 󰑞 󰑟
F0460   󰑠 󰑡 󰑢 󰑣 󰑤 󰑥 󰑦 󰑧 󰑨 󰑩 󰑪 󰑫 󰑬 󰑭 󰑮 󰑯
F0470   󰑰 󰑱 󰑲 󰑳 󰑴 󰑵 󰑶 󰑷 󰑸 󰑹 󰑺 󰑻 󰑼 󰑽 󰑾 󰑿
F0480   󰒀 󰒁 󰒂 󰒃 󰒄 󰒅 󰒆 󰒇 󰒈 󰒉 󰒊 󰒋 󰒌 󰒍 󰒎 󰒏
F0490   󰒐 󰒑 󰒒 󰒓 󰒔 󰒕 󰒖 󰒗 󰒘 󰒙 󰒚 󰒛 󰒜 󰒝 󰒞 󰒟
F04A0   󰒠 󰒡 󰒢 󰒣 󰒤 󰒥 󰒦 󰒧 󰒨 󰒩 󰒪 󰒫 󰒬 󰒭 󰒮 󰒯
F04B0   󰒰 󰒱 󰒲 󰒳 󰒴 󰒵 󰒶 󰒷 󰒸 󰒹 󰒺 󰒻 󰒼 󰒽 󰒾 󰒿
F04C0   󰓀 󰓁 󰓂 󰓃 󰓄 󰓅 󰓆 󰓇 󰓈 󰓉 󰓊 󰓋 󰓌 󰓍 󰓎 󰓏
F04D0   󰓐 󰓑 󰓒 󰓓 󰓔 󰓕 󰓖 󰓗 󰓘 󰓙 󰓚 󰓛 󰓜 󰓝 󰓞 󰓟
F04E0   󰓠 󰓡 󰓢 󰓣 󰓤 󰓥 󰓦 󰓧 󰓨 󰓩 󰓪 󰓫 󰓬 󰓭 󰓮 󰓯
F04F0   󰓰 󰓱 󰓲 󰓳 󰓴 󰓵 󰓶 󰓷 󰓸 󰓹 󰓺 󰓻 󰓼 󰓽 󰓾 󰓿
F0500   󰔀 󰔁 󰔂 󰔃 󰔄 󰔅 󰔆 󰔇 󰔈 󰔉 󰔊 󰔋 󰔌 󰔍 󰔎 󰔏
F0510   󰔐 󰔑 󰔒 󰔓 󰔔 󰔕 󰔖 󰔗 󰔘 󰔙 󰔚 󰔛 󰔜 󰔝 󰔞 󰔟
F0520   󰔠 󰔡 󰔢 󰔣 󰔤 󰔥 󰔦 󰔧 󰔨 󰔩 󰔪 󰔫 󰔬 󰔭 󰔮 󰔯
F0530   󰔰 󰔱 󰔲 󰔳 󰔴 󰔵 󰔶 󰔷 󰔸 󰔹 󰔺 󰔻 󰔼 󰔽 󰔾 󰔿
F0540   󰕀 󰕁 󰕂 󰕃 󰕄 󰕅 󰕆 󰕇 󰕈 󰕉 󰕊 󰕋 󰕌 󰕍 󰕎 󰕏
F0550   󰕐 󰕑 󰕒 󰕓 󰕔 󰕕 󰕖 󰕗 󰕘 󰕙 󰕚 󰕛 󰕜 󰕝 󰕞 󰕟
F0560   󰕠 󰕡 󰕢 󰕣 󰕤 󰕥 󰕦 󰕧 󰕨 󰕩 󰕪 󰕫 󰕬 󰕭 󰕮 󰕯
F0570   󰕰 󰕱 󰕲 󰕳 󰕴 󰕵 󰕶 󰕷 󰕸 󰕹 󰕺 󰕻 󰕼 󰕽 󰕾 󰕿
F0580   󰖀 󰖁 󰖂 󰖃 󰖄 󰖅 󰖆 󰖇 󰖈 󰖉 󰖊 󰖋 󰖌 󰖍 󰖎 󰖏
F0590   󰖐 󰖑 󰖒 󰖓 󰖔 󰖕 󰖖 󰖗 󰖘 󰖙 󰖚 󰖛 󰖜 󰖝 󰖞 󰖟
F05A0   󰖠 󰖡 󰖢 󰖣 󰖤 󰖥 󰖦 󰖧 󰖨 󰖩 󰖪 󰖫 󰖬 󰖭 󰖮 󰖯
F05B0   󰖰 󰖱 󰖲 󰖳 󰖴 󰖵 󰖶 󰖷 󰖸 󰖹 󰖺 󰖻 󰖼 󰖽 󰖾 󰖿
F05C0   󰗀 󰗁 󰗂 󰗃 󰗄 󰗅 󰗆 󰗇 󰗈 󰗉 󰗊 󰗋 󰗌 󰗍 󰗎 󰗏
F05D0   󰗐 󰗑 󰗒 󰗓 󰗔 󰗕 󰗖 󰗗 󰗘 󰗙 󰗚 󰗛 󰗜 󰗝 󰗞 󰗟
F05E0   󰗠 󰗡 󰗢 󰗣 󰗤 󰗥 󰗦 󰗧 󰗨 󰗩 󰗪 󰗫 󰗬 󰗭 󰗮 󰗯
F05F0   󰗰 󰗱 󰗲 󰗳 󰗴 󰗵 󰗶 󰗷 󰗸 󰗹 󰗺 󰗻 󰗼 󰗽 󰗾 󰗿
F0600   󰘀 󰘁 󰘂 󰘃 󰘄 󰘅 󰘆 󰘇 󰘈 󰘉 󰘊 󰘋 󰘌 󰘍 󰘎 󰘏
F0610   󰘐 󰘑 󰘒 󰘓 󰘔 󰘕 󰘖 󰘗 󰘘 󰘙 󰘚 󰘛 󰘜 󰘝 󰘞 󰘟
F0620   󰘠 󰘡 󰘢 󰘣 󰘤 󰘥 󰘦 󰘧 󰘨 󰘩 󰘪 󰘫 󰘬 󰘭 󰘮 󰘯
F0630   󰘰 󰘱 󰘲 󰘳 󰘴 󰘵 󰘶 󰘷 󰘸 󰘹 󰘺 󰘻 󰘼 󰘽 󰘾 󰘿
F0640   󰙀 󰙁 󰙂 󰙃 󰙄 󰙅 󰙆 󰙇 󰙈 󰙉 󰙊 󰙋 󰙌 󰙍 󰙎 󰙏
F0650   󰙐 󰙑 󰙒 󰙓 󰙔 󰙕 󰙖 󰙗 󰙘 󰙙 󰙚 󰙛 󰙜 󰙝 󰙞 󰙟
F0660   󰙠 󰙡 󰙢 󰙣 󰙤 󰙥 󰙦 󰙧 󰙨 󰙩 󰙪 󰙫 󰙬 󰙭 󰙮 󰙯
F0670   󰙰 󰙱 󰙲 󰙳 󰙴 󰙵 󰙶 󰙷 󰙸 󰙹 󰙺 󰙻 󰙼 󰙽 󰙾 󰙿
F0680   󰚀 󰚁 󰚂 󰚃 󰚄 󰚅 󰚆 󰚇 󰚈 󰚉 󰚊 󰚋 󰚌 󰚍 󰚎 󰚏
F0690   󰚐 󰚑 󰚒 󰚓 󰚔 󰚕 󰚖 󰚗 󰚘 󰚙 󰚚 󰚛 󰚜 󰚝 󰚞 󰚟
F06A0   󰚠 󰚡 󰚢 󰚣 󰚤 󰚥 󰚦 󰚧 󰚨 󰚩 󰚪 󰚫 󰚬 󰚭 󰚮 󰚯
F06B0   󰚰 󰚱 󰚲 󰚳 󰚴 󰚵 󰚶 󰚷 󰚸 󰚹 󰚺 󰚻 󰚼 󰚽 󰚾 󰚿
F06C0   󰛀 󰛁 󰛂 󰛃 󰛄 󰛅 󰛆 󰛇 󰛈 󰛉 󰛊 󰛋 󰛌 󰛍 󰛎 󰛏
F06D0   󰛐 󰛑 󰛒 󰛓 󰛔 󰛕 󰛖 󰛗 󰛘 󰛙 󰛚 󰛛 󰛜 󰛝 󰛞 󰛟
F06E0   󰛠 󰛡 󰛢 󰛣 󰛤 󰛥 󰛦 󰛧 󰛨 󰛩 󰛪 󰛫 󰛬 󰛭 󰛮 󰛯
F06F0   󰛰 󰛱 󰛲 󰛳 󰛴 󰛵 󰛶 󰛷 󰛸 󰛹 󰛺 󰛻 󰛼 󰛽 󰛾 󰛿
F0700   󰜀 󰜁 󰜂 󰜃 󰜄 󰜅 󰜆 󰜇 󰜈 󰜉 󰜊 󰜋 󰜌 󰜍 󰜎 󰜏
F0710   󰜐 󰜑 󰜒 󰜓 󰜔 󰜕 󰜖 󰜗 󰜘 󰜙 󰜚 󰜛 󰜜 󰜝 󰜞 󰜟
F0720   󰜠 󰜡 󰜢 󰜣 󰜤 󰜥 󰜦 󰜧 󰜨 󰜩 󰜪 󰜫 󰜬 󰜭 󰜮 󰜯
F0730   󰜰 󰜱 󰜲 󰜳 󰜴 󰜵 󰜶 󰜷 󰜸 󰜹 󰜺 󰜻 󰜼 󰜽 󰜾 󰜿
F0740   󰝀 󰝁 󰝂 󰝃 󰝄 󰝅 󰝆 󰝇 󰝈 󰝉 󰝊 󰝋 󰝌 󰝍 󰝎 󰝏
F0750   󰝐 󰝑 󰝒 󰝓 󰝔 󰝕 󰝖 󰝗 󰝘 󰝙 󰝚 󰝛 󰝜 󰝝 󰝞 󰝟
F0760   󰝠 󰝡 󰝢 󰝣 󰝤 󰝥 󰝦 󰝧 󰝨 󰝩 󰝪 󰝫 󰝬 󰝭 󰝮 󰝯
F0770   󰝰 󰝱 󰝲 󰝳 󰝴 󰝵 󰝶 󰝷 󰝸 󰝹 󰝺 󰝻 󰝼 󰝽 󰝾 󰝿
F0780   󰞀 󰞁 󰞂 󰞃 󰞄 󰞅 󰞆 󰞇 󰞈 󰞉 󰞊 󰞋 󰞌 󰞍 󰞎 󰞏
F0790   󰞐 󰞑 󰞒 󰞓 󰞔 󰞕 󰞖 󰞗 󰞘 󰞙 󰞚 󰞛 󰞜 󰞝 󰞞 󰞟
F07A0   󰞠 󰞡 󰞢 󰞣 󰞤 󰞥 󰞦 󰞧 󰞨 󰞩 󰞪 󰞫 󰞬 󰞭 󰞮 󰞯
F07B0   󰞰 󰞱 󰞲 󰞳 󰞴 󰞵 󰞶 󰞷 󰞸 󰞹 󰞺 󰞻 󰞼 󰞽 󰞾 󰞿
F07C0   󰟀 󰟁 󰟂 󰟃 󰟄 󰟅 󰟆 󰟇 󰟈 󰟉 󰟊 󰟋 󰟌 󰟍 󰟎 󰟏
F07D0   󰟐 󰟑 󰟒 󰟓 󰟔 󰟕 󰟖 󰟗 󰟘 󰟙 󰟚 󰟛 󰟜 󰟝 󰟞 󰟟
F07E0   󰟠 󰟡 󰟢 󰟣 󰟤 󰟥 󰟦 󰟧 󰟨 󰟩 󰟪 󰟫 󰟬 󰟭 󰟮 󰟯
F07F0   󰟰 󰟱 󰟲 󰟳 󰟴 󰟵 󰟶 󰟷 󰟸 󰟹 󰟺 󰟻 󰟼 󰟽 󰟾 󰟿

*** F0800–F0BFF
F0800   󰠀 󰠁 󰠂 󰠃 󰠄 󰠅 󰠆 󰠇 󰠈 󰠉 󰠊 󰠋 󰠌 󰠍 󰠎 󰠏
F0810   󰠐 󰠑 󰠒 󰠓 󰠔 󰠕 󰠖 󰠗 󰠘 󰠙 󰠚 󰠛 󰠜 󰠝 󰠞 󰠟
F0820   󰠠 󰠡 󰠢 󰠣 󰠤 󰠥 󰠦 󰠧 󰠨 󰠩 󰠪 󰠫 󰠬 󰠭 󰠮 󰠯
F0830   󰠰 󰠱 󰠲 󰠳 󰠴 󰠵 󰠶 󰠷 󰠸 󰠹 󰠺 󰠻 󰠼 󰠽 󰠾 󰠿
F0840   󰡀 󰡁 󰡂 󰡃 󰡄 󰡅 󰡆 󰡇 󰡈 󰡉 󰡊 󰡋 󰡌 󰡍 󰡎 󰡏
F0850   󰡐 󰡑 󰡒 󰡓 󰡔 󰡕 󰡖 󰡗 󰡘 󰡙 󰡚 󰡛 󰡜 󰡝 󰡞 󰡟
F0860   󰡠 󰡡 󰡢 󰡣 󰡤 󰡥 󰡦 󰡧 󰡨 󰡩 󰡪 󰡫 󰡬 󰡭 󰡮 󰡯
F0870   󰡰 󰡱 󰡲 󰡳 󰡴 󰡵 󰡶 󰡷 󰡸 󰡹 󰡺 󰡻 󰡼 󰡽 󰡾 󰡿
F0880   󰢀 󰢁 󰢂 󰢃 󰢄 󰢅 󰢆 󰢇 󰢈 󰢉 󰢊 󰢋 󰢌 󰢍 󰢎 󰢏
F0890   󰢐 󰢑 󰢒 󰢓 󰢔 󰢕 󰢖 󰢗 󰢘 󰢙 󰢚 󰢛 󰢜 󰢝 󰢞 󰢟
F08A0   󰢠 󰢡 󰢢 󰢣 󰢤 󰢥 󰢦 󰢧 󰢨 󰢩 󰢪 󰢫 󰢬 󰢭 󰢮 󰢯
F08B0   󰢰 󰢱 󰢲 󰢳 󰢴 󰢵 󰢶 󰢷 󰢸 󰢹 󰢺 󰢻 󰢼 󰢽 󰢾 󰢿
F08C0   󰣀 󰣁 󰣂 󰣃 󰣄 󰣅 󰣆 󰣇 󰣈 󰣉 󰣊 󰣋 󰣌 󰣍 󰣎 󰣏
F08D0   󰣐 󰣑 󰣒 󰣓 󰣔 󰣕 󰣖 󰣗 󰣘 󰣙 󰣚 󰣛 󰣜 󰣝 󰣞 󰣟
F08E0   󰣠 󰣡 󰣢 󰣣 󰣤 󰣥 󰣦 󰣧 󰣨 󰣩 󰣪 󰣫 󰣬 󰣭 󰣮 󰣯
F08F0   󰣰 󰣱 󰣲 󰣳 󰣴 󰣵 󰣶 󰣷 󰣸 󰣹 󰣺 󰣻 󰣼 󰣽 󰣾 󰣿
F0900   󰤀 󰤁 󰤂 󰤃 󰤄 󰤅 󰤆 󰤇 󰤈 󰤉 󰤊 󰤋 󰤌 󰤍 󰤎 󰤏
F0910   󰤐 󰤑 󰤒 󰤓 󰤔 󰤕 󰤖 󰤗 󰤘 󰤙 󰤚 󰤛 󰤜 󰤝 󰤞 󰤟
F0920   󰤠 󰤡 󰤢 󰤣 󰤤 󰤥 󰤦 󰤧 󰤨 󰤩 󰤪 󰤫 󰤬 󰤭 󰤮 󰤯
F0930   󰤰 󰤱 󰤲 󰤳 󰤴 󰤵 󰤶 󰤷 󰤸 󰤹 󰤺 󰤻 󰤼 󰤽 󰤾 󰤿
F0940   󰥀 󰥁 󰥂 󰥃 󰥄 󰥅 󰥆 󰥇 󰥈 󰥉 󰥊 󰥋 󰥌 󰥍 󰥎 󰥏
F0950   󰥐 󰥑 󰥒 󰥓 󰥔 󰥕 󰥖 󰥗 󰥘 󰥙 󰥚 󰥛 󰥜 󰥝 󰥞 󰥟
F0960   󰥠 󰥡 󰥢 󰥣 󰥤 󰥥 󰥦 󰥧 󰥨 󰥩 󰥪 󰥫 󰥬 󰥭 󰥮 󰥯
F0970   󰥰 󰥱 󰥲 󰥳 󰥴 󰥵 󰥶 󰥷 󰥸 󰥹 󰥺 󰥻 󰥼 󰥽 󰥾 󰥿
F0980   󰦀 󰦁 󰦂 󰦃 󰦄 󰦅 󰦆 󰦇 󰦈 󰦉 󰦊 󰦋 󰦌 󰦍 󰦎 󰦏
F0990   󰦐 󰦑 󰦒 󰦓 󰦔 󰦕 󰦖 󰦗 󰦘 󰦙 󰦚 󰦛 󰦜 󰦝 󰦞 󰦟
F09A0   󰦠 󰦡 󰦢 󰦣 󰦤 󰦥 󰦦 󰦧 󰦨 󰦩 󰦪 󰦫 󰦬 󰦭 󰦮 󰦯
F09B0   󰦰 󰦱 󰦲 󰦳 󰦴 󰦵 󰦶 󰦷 󰦸 󰦹 󰦺 󰦻 󰦼 󰦽 󰦾 󰦿
F09C0   󰧀 󰧁 󰧂 󰧃 󰧄 󰧅 󰧆 󰧇 󰧈 󰧉 󰧊 󰧋 󰧌 󰧍 󰧎 󰧏
F09D0   󰧐 󰧑 󰧒 󰧓 󰧔 󰧕 󰧖 󰧗 󰧘 󰧙 󰧚 󰧛 󰧜 󰧝 󰧞 󰧟
F09E0   󰧠 󰧡 󰧢 󰧣 󰧤 󰧥 󰧦 󰧧 󰧨 󰧩 󰧪 󰧫 󰧬 󰧭 󰧮 󰧯
F09F0   󰧰 󰧱 󰧲 󰧳 󰧴 󰧵 󰧶 󰧷 󰧸 󰧹 󰧺 󰧻 󰧼 󰧽 󰧾 󰧿
F0A00   󰨀 󰨁 󰨂 󰨃 󰨄 󰨅 󰨆 󰨇 󰨈 󰨉 󰨊 󰨋 󰨌 󰨍 󰨎 󰨏
F0A10   󰨐 󰨑 󰨒 󰨓 󰨔 󰨕 󰨖 󰨗 󰨘 󰨙 󰨚 󰨛 󰨜 󰨝 󰨞 󰨟
F0A20   󰨠 󰨡 󰨢 󰨣 󰨤 󰨥 󰨦 󰨧 󰨨 󰨩 󰨪 󰨫 󰨬 󰨭 󰨮 󰨯
F0A30   󰨰 󰨱 󰨲 󰨳 󰨴 󰨵 󰨶 󰨷 󰨸 󰨹 󰨺 󰨻 󰨼 󰨽 󰨾 󰨿
F0A40   󰩀 󰩁 󰩂 󰩃 󰩄 󰩅 󰩆 󰩇 󰩈 󰩉 󰩊 󰩋 󰩌 󰩍 󰩎 󰩏
F0A50   󰩐 󰩑 󰩒 󰩓 󰩔 󰩕 󰩖 󰩗 󰩘 󰩙 󰩚 󰩛 󰩜 󰩝 󰩞 󰩟
F0A60   󰩠 󰩡 󰩢 󰩣 󰩤 󰩥 󰩦 󰩧 󰩨 󰩩 󰩪 󰩫 󰩬 󰩭 󰩮 󰩯
F0A70   󰩰 󰩱 󰩲 󰩳 󰩴 󰩵 󰩶 󰩷 󰩸 󰩹 󰩺 󰩻 󰩼 󰩽 󰩾 󰩿
F0A80   󰪀 󰪁 󰪂 󰪃 󰪄 󰪅 󰪆 󰪇 󰪈 󰪉 󰪊 󰪋 󰪌 󰪍 󰪎 󰪏
F0A90   󰪐 󰪑 󰪒 󰪓 󰪔 󰪕 󰪖 󰪗 󰪘 󰪙 󰪚 󰪛 󰪜 󰪝 󰪞 󰪟
F0AA0   󰪠 󰪡 󰪢 󰪣 󰪤 󰪥 󰪦 󰪧 󰪨 󰪩 󰪪 󰪫 󰪬 󰪭 󰪮 󰪯
F0AB0   󰪰 󰪱 󰪲 󰪳 󰪴 󰪵 󰪶 󰪷 󰪸 󰪹 󰪺 󰪻 󰪼 󰪽 󰪾 󰪿
F0AC0   󰫀 󰫁 󰫂 󰫃 󰫄 󰫅 󰫆 󰫇 󰫈 󰫉 󰫊 󰫋 󰫌 󰫍 󰫎 󰫏
F0AD0   󰫐 󰫑 󰫒 󰫓 󰫔 󰫕 󰫖 󰫗 󰫘 󰫙 󰫚 󰫛 󰫜 󰫝 󰫞 󰫟
F0AE0   󰫠 󰫡 󰫢 󰫣 󰫤 󰫥 󰫦 󰫧 󰫨 󰫩 󰫪 󰫫 󰫬 󰫭 󰫮 󰫯
F0AF0   󰫰 󰫱 󰫲 󰫳 󰫴 󰫵 󰫶 󰫷 󰫸 󰫹 󰫺 󰫻 󰫼 󰫽 󰫾 󰫿
F0B00   󰬀 󰬁 󰬂 󰬃 󰬄 󰬅 󰬆 󰬇 󰬈 󰬉 󰬊 󰬋 󰬌 󰬍 󰬎 󰬏
F0B10   󰬐 󰬑 󰬒 󰬓 󰬔 󰬕 󰬖 󰬗 󰬘 󰬙 󰬚 󰬛 󰬜 󰬝 󰬞 󰬟
F0B20   󰬠 󰬡 󰬢 󰬣 󰬤 󰬥 󰬦 󰬧 󰬨 󰬩 󰬪 󰬫 󰬬 󰬭 󰬮 󰬯
F0B30   󰬰 󰬱 󰬲 󰬳 󰬴 󰬵 󰬶 󰬷 󰬸 󰬹 󰬺 󰬻 󰬼 󰬽 󰬾 󰬿
F0B40   󰭀 󰭁 󰭂 󰭃 󰭄 󰭅 󰭆 󰭇 󰭈 󰭉 󰭊 󰭋 󰭌 󰭍 󰭎 󰭏
F0B50   󰭐 󰭑 󰭒 󰭓 󰭔 󰭕 󰭖 󰭗 󰭘 󰭙 󰭚 󰭛 󰭜 󰭝 󰭞 󰭟
F0B60   󰭠 󰭡 󰭢 󰭣 󰭤 󰭥 󰭦 󰭧 󰭨 󰭩 󰭪 󰭫 󰭬 󰭭 󰭮 󰭯
F0B70   󰭰 󰭱 󰭲 󰭳 󰭴 󰭵 󰭶 󰭷 󰭸 󰭹 󰭺 󰭻 󰭼 󰭽 󰭾 󰭿
F0B80   󰮀 󰮁 󰮂 󰮃 󰮄 󰮅 󰮆 󰮇 󰮈 󰮉 󰮊 󰮋 󰮌 󰮍 󰮎 󰮏
F0B90   󰮐 󰮑 󰮒 󰮓 󰮔 󰮕 󰮖 󰮗 󰮘 󰮙 󰮚 󰮛 󰮜 󰮝 󰮞 󰮟
F0BA0   󰮠 󰮡 󰮢 󰮣 󰮤 󰮥 󰮦 󰮧 󰮨 󰮩 󰮪 󰮫 󰮬 󰮭 󰮮 󰮯
F0BB0   󰮰 󰮱 󰮲 󰮳 󰮴 󰮵 󰮶 󰮷 󰮸 󰮹 󰮺 󰮻 󰮼 󰮽 󰮾 󰮿
F0BC0   󰯀 󰯁 󰯂 󰯃 󰯄 󰯅 󰯆 󰯇 󰯈 󰯉 󰯊 󰯋 󰯌 󰯍 󰯎 󰯏
F0BD0   󰯐 󰯑 󰯒 󰯓 󰯔 󰯕 󰯖 󰯗 󰯘 󰯙 󰯚 󰯛 󰯜 󰯝 󰯞 󰯟
F0BE0   󰯠 󰯡 󰯢 󰯣 󰯤 󰯥 󰯦 󰯧 󰯨 󰯩 󰯪 󰯫 󰯬 󰯭 󰯮 󰯯
F0BF0   󰯰 󰯱 󰯲 󰯳 󰯴 󰯵 󰯶 󰯷 󰯸 󰯹 󰯺 󰯻 󰯼 󰯽 󰯾 󰯿

*** F0C00–F0FFF
F0C00   󰰀 󰰁 󰰂 󰰃 󰰄 󰰅 󰰆 󰰇 󰰈 󰰉 󰰊 󰰋 󰰌 󰰍 󰰎 󰰏
F0C10   󰰐 󰰑 󰰒 󰰓 󰰔 󰰕 󰰖 󰰗 󰰘 󰰙 󰰚 󰰛 󰰜 󰰝 󰰞 󰰟
F0C20   󰰠 󰰡 󰰢 󰰣 󰰤 󰰥 󰰦 󰰧 󰰨 󰰩 󰰪 󰰫 󰰬 󰰭 󰰮 󰰯
F0C30   󰰰 󰰱 󰰲 󰰳 󰰴 󰰵 󰰶 󰰷 󰰸 󰰹 󰰺 󰰻 󰰼 󰰽 󰰾 󰰿
F0C40   󰱀 󰱁 󰱂 󰱃 󰱄 󰱅 󰱆 󰱇 󰱈 󰱉 󰱊 󰱋 󰱌 󰱍 󰱎 󰱏
F0C50   󰱐 󰱑 󰱒 󰱓 󰱔 󰱕 󰱖 󰱗 󰱘 󰱙 󰱚 󰱛 󰱜 󰱝 󰱞 󰱟
F0C60   󰱠 󰱡 󰱢 󰱣 󰱤 󰱥 󰱦 󰱧 󰱨 󰱩 󰱪 󰱫 󰱬 󰱭 󰱮 󰱯
F0C70   󰱰 󰱱 󰱲 󰱳 󰱴 󰱵 󰱶 󰱷 󰱸 󰱹 󰱺 󰱻 󰱼 󰱽 󰱾 󰱿
F0C80   󰲀 󰲁 󰲂 󰲃 󰲄 󰲅 󰲆 󰲇 󰲈 󰲉 󰲊 󰲋 󰲌 󰲍 󰲎 󰲏
F0C90   󰲐 󰲑 󰲒 󰲓 󰲔 󰲕 󰲖 󰲗 󰲘 󰲙 󰲚 󰲛 󰲜 󰲝 󰲞 󰲟
F0CA0   󰲠 󰲡 󰲢 󰲣 󰲤 󰲥 󰲦 󰲧 󰲨 󰲩 󰲪 󰲫 󰲬 󰲭 󰲮 󰲯
F0CB0   󰲰 󰲱 󰲲 󰲳 󰲴 󰲵 󰲶 󰲷 󰲸 󰲹 󰲺 󰲻 󰲼 󰲽 󰲾 󰲿
F0CC0   󰳀 󰳁 󰳂 󰳃 󰳄 󰳅 󰳆 󰳇 󰳈 󰳉 󰳊 󰳋 󰳌 󰳍 󰳎 󰳏
F0CD0   󰳐 󰳑 󰳒 󰳓 󰳔 󰳕 󰳖 󰳗 󰳘 󰳙 󰳚 󰳛 󰳜 󰳝 󰳞 󰳟
F0CE0   󰳠 󰳡 󰳢 󰳣 󰳤 󰳥 󰳦 󰳧 󰳨 󰳩 󰳪 󰳫 󰳬 󰳭 󰳮 󰳯
F0CF0   󰳰 󰳱 󰳲 󰳳 󰳴 󰳵 󰳶 󰳷 󰳸 󰳹 󰳺 󰳻 󰳼 󰳽 󰳾 󰳿
F0D00   󰴀 󰴁 󰴂 󰴃 󰴄 󰴅 󰴆 󰴇 󰴈 󰴉 󰴊 󰴋 󰴌 󰴍 󰴎 󰴏
F0D10   󰴐 󰴑 󰴒 󰴓 󰴔 󰴕 󰴖 󰴗 󰴘 󰴙 󰴚 󰴛 󰴜 󰴝 󰴞 󰴟
F0D20   󰴠 󰴡 󰴢 󰴣 󰴤 󰴥 󰴦 󰴧 󰴨 󰴩 󰴪 󰴫 󰴬 󰴭 󰴮 󰴯
F0D30   󰴰 󰴱 󰴲 󰴳 󰴴 󰴵 󰴶 󰴷 󰴸 󰴹 󰴺 󰴻 󰴼 󰴽 󰴾 󰴿
F0D40   󰵀 󰵁 󰵂 󰵃 󰵄 󰵅 󰵆 󰵇 󰵈 󰵉 󰵊 󰵋 󰵌 󰵍 󰵎 󰵏
F0D50   󰵐 󰵑 󰵒 󰵓 󰵔 󰵕 󰵖 󰵗 󰵘 󰵙 󰵚 󰵛 󰵜 󰵝 󰵞 󰵟
F0D60   󰵠 󰵡 󰵢 󰵣 󰵤 󰵥 󰵦 󰵧 󰵨 󰵩 󰵪 󰵫 󰵬 󰵭 󰵮 󰵯
F0D70   󰵰 󰵱 󰵲 󰵳 󰵴 󰵵 󰵶 󰵷 󰵸 󰵹 󰵺 󰵻 󰵼 󰵽 󰵾 󰵿
F0D80   󰶀 󰶁 󰶂 󰶃 󰶄 󰶅 󰶆 󰶇 󰶈 󰶉 󰶊 󰶋 󰶌 󰶍 󰶎 󰶏
F0D90   󰶐 󰶑 󰶒 󰶓 󰶔 󰶕 󰶖 󰶗 󰶘 󰶙 󰶚 󰶛 󰶜 󰶝 󰶞 󰶟
F0DA0   󰶠 󰶡 󰶢 󰶣 󰶤 󰶥 󰶦 󰶧 󰶨 󰶩 󰶪 󰶫 󰶬 󰶭 󰶮 󰶯
F0DB0   󰶰 󰶱 󰶲 󰶳 󰶴 󰶵 󰶶 󰶷 󰶸 󰶹 󰶺 󰶻 󰶼 󰶽 󰶾 󰶿
F0DC0   󰷀 󰷁 󰷂 󰷃 󰷄 󰷅 󰷆 󰷇 󰷈 󰷉 󰷊 󰷋 󰷌 󰷍 󰷎 󰷏
F0DD0   󰷐 󰷑 󰷒 󰷓 󰷔 󰷕 󰷖 󰷗 󰷘 󰷙 󰷚 󰷛 󰷜 󰷝 󰷞 󰷟
F0DE0   󰷠 󰷡 󰷢 󰷣 󰷤 󰷥 󰷦 󰷧 󰷨 󰷩 󰷪 󰷫 󰷬 󰷭 󰷮 󰷯
F0DF0   󰷰 󰷱 󰷲 󰷳 󰷴 󰷵 󰷶 󰷷 󰷸 󰷹 󰷺 󰷻 󰷼 󰷽 󰷾 󰷿
F0E00   󰸀 󰸁 󰸂 󰸃 󰸄 󰸅 󰸆 󰸇 󰸈 󰸉 󰸊 󰸋 󰸌 󰸍 󰸎 󰸏
F0E10   󰸐 󰸑 󰸒 󰸓 󰸔 󰸕 󰸖 󰸗 󰸘 󰸙 󰸚 󰸛 󰸜 󰸝 󰸞 󰸟
F0E20   󰸠 󰸡 󰸢 󰸣 󰸤 󰸥 󰸦 󰸧 󰸨 󰸩 󰸪 󰸫 󰸬 󰸭 󰸮 󰸯
F0E30   󰸰 󰸱 󰸲 󰸳 󰸴 󰸵 󰸶 󰸷 󰸸 󰸹 󰸺 󰸻 󰸼 󰸽 󰸾 󰸿
F0E40   󰹀 󰹁 󰹂 󰹃 󰹄 󰹅 󰹆 󰹇 󰹈 󰹉 󰹊 󰹋 󰹌 󰹍 󰹎 󰹏
F0E50   󰹐 󰹑 󰹒 󰹓 󰹔 󰹕 󰹖 󰹗 󰹘 󰹙 󰹚 󰹛 󰹜 󰹝 󰹞 󰹟
F0E60   󰹠 󰹡 󰹢 󰹣 󰹤 󰹥 󰹦 󰹧 󰹨 󰹩 󰹪 󰹫 󰹬 󰹭 󰹮 󰹯
F0E70   󰹰 󰹱 󰹲 󰹳 󰹴 󰹵 󰹶 󰹷 󰹸 󰹹 󰹺 󰹻 󰹼 󰹽 󰹾 󰹿
F0E80   󰺀 󰺁 󰺂 󰺃 󰺄 󰺅 󰺆 󰺇 󰺈 󰺉 󰺊 󰺋 󰺌 󰺍 󰺎 󰺏
F0E90   󰺐 󰺑 󰺒 󰺓 󰺔 󰺕 󰺖 󰺗 󰺘 󰺙 󰺚 󰺛 󰺜 󰺝 󰺞 󰺟
F0EA0   󰺠 󰺡 󰺢 󰺣 󰺤 󰺥 󰺦 󰺧 󰺨 󰺩 󰺪 󰺫 󰺬 󰺭 󰺮 󰺯
F0EB0   󰺰 󰺱 󰺲 󰺳 󰺴 󰺵 󰺶 󰺷 󰺸 󰺹 󰺺 󰺻 󰺼 󰺽 󰺾 󰺿
F0EC0   󰻀 󰻁 󰻂 󰻃 󰻄 󰻅 󰻆 󰻇 󰻈 󰻉 󰻊 󰻋 󰻌 󰻍 󰻎 󰻏
F0ED0   󰻐 󰻑 󰻒 󰻓 󰻔 󰻕 󰻖 󰻗 󰻘 󰻙 󰻚 󰻛 󰻜 󰻝 󰻞 󰻟
F0EE0   󰻠 󰻡 󰻢 󰻣 󰻤 󰻥 󰻦 󰻧 󰻨 󰻩 󰻪 󰻫 󰻬 󰻭 󰻮 󰻯
F0EF0   󰻰 󰻱 󰻲 󰻳 󰻴 󰻵 󰻶 󰻷 󰻸 󰻹 󰻺 󰻻 󰻼 󰻽 󰻾 󰻿
F0F00   󰼀 󰼁 󰼂 󰼃 󰼄 󰼅 󰼆 󰼇 󰼈 󰼉 󰼊 󰼋 󰼌 󰼍 󰼎 󰼏
F0F10   󰼐 󰼑 󰼒 󰼓 󰼔 󰼕 󰼖 󰼗 󰼘 󰼙 󰼚 󰼛 󰼜 󰼝 󰼞 󰼟
F0F20   󰼠 󰼡 󰼢 󰼣 󰼤 󰼥 󰼦 󰼧 󰼨 󰼩 󰼪 󰼫 󰼬 󰼭 󰼮 󰼯
F0F30   󰼰 󰼱 󰼲 󰼳 󰼴 󰼵 󰼶 󰼷 󰼸 󰼹 󰼺 󰼻 󰼼 󰼽 󰼾 󰼿
F0F40   󰽀 󰽁 󰽂 󰽃 󰽄 󰽅 󰽆 󰽇 󰽈 󰽉 󰽊 󰽋 󰽌 󰽍 󰽎 󰽏
F0F50   󰽐 󰽑 󰽒 󰽓 󰽔 󰽕 󰽖 󰽗 󰽘 󰽙 󰽚 󰽛 󰽜 󰽝 󰽞 󰽟
F0F60   󰽠 󰽡 󰽢 󰽣 󰽤 󰽥 󰽦 󰽧 󰽨 󰽩 󰽪 󰽫 󰽬 󰽭 󰽮 󰽯
F0F70   󰽰 󰽱 󰽲 󰽳 󰽴 󰽵 󰽶 󰽷 󰽸 󰽹 󰽺 󰽻 󰽼 󰽽 󰽾 󰽿
F0F80   󰾀 󰾁 󰾂 󰾃 󰾄 󰾅 󰾆 󰾇 󰾈 󰾉 󰾊 󰾋 󰾌 󰾍 󰾎 󰾏
F0F90   󰾐 󰾑 󰾒 󰾓 󰾔 󰾕 󰾖 󰾗 󰾘 󰾙 󰾚 󰾛 󰾜 󰾝 󰾞 󰾟
F0FA0   󰾠 󰾡 󰾢 󰾣 󰾤 󰾥 󰾦 󰾧 󰾨 󰾩 󰾪 󰾫 󰾬 󰾭 󰾮 󰾯
F0FB0   󰾰 󰾱 󰾲 󰾳 󰾴 󰾵 󰾶 󰾷 󰾸 󰾹 󰾺 󰾻 󰾼 󰾽 󰾾 󰾿
F0FC0   󰿀 󰿁 󰿂 󰿃 󰿄 󰿅 󰿆 󰿇 󰿈 󰿉 󰿊 󰿋 󰿌 󰿍 󰿎 󰿏
F0FD0   󰿐 󰿑 󰿒 󰿓 󰿔 󰿕 󰿖 󰿗 󰿘 󰿙 󰿚 󰿛 󰿜 󰿝 󰿞 󰿟
F0FE0   󰿠 󰿡 󰿢 󰿣 󰿤 󰿥 󰿦 󰿧 󰿨 󰿩 󰿪 󰿫 󰿬 󰿭 󰿮 󰿯
F0FF0   󰿰 󰿱 󰿲 󰿳 󰿴 󰿵 󰿶 󰿷 󰿸 󰿹 󰿺 󰿻 󰿼 󰿽 󰿾 󰿿

*** F1000–F13FF
F1000   󱀀 󱀁 󱀂 󱀃 󱀄 󱀅 󱀆 󱀇 󱀈 󱀉 󱀊 󱀋 󱀌 󱀍 󱀎 󱀏
F1010   󱀐 󱀑 󱀒 󱀓 󱀔 󱀕 󱀖 󱀗 󱀘 󱀙 󱀚 󱀛 󱀜 󱀝 󱀞 󱀟
F1020   󱀠 󱀡 󱀢 󱀣 󱀤 󱀥 󱀦 󱀧 󱀨 󱀩 󱀪 󱀫 󱀬 󱀭 󱀮 󱀯
F1030   󱀰 󱀱 󱀲 󱀳 󱀴 󱀵 󱀶 󱀷 󱀸 󱀹 󱀺 󱀻 󱀼 󱀽 󱀾 󱀿
F1040   󱁀 󱁁 󱁂 󱁃 󱁄 󱁅 󱁆 󱁇 󱁈 󱁉 󱁊 󱁋 󱁌 󱁍 󱁎 󱁏
F1050   󱁐 󱁑 󱁒 󱁓 󱁔 󱁕 󱁖 󱁗 󱁘 󱁙 󱁚 󱁛 󱁜 󱁝 󱁞 󱁟
F1060   󱁠 󱁡 󱁢 󱁣 󱁤 󱁥 󱁦 󱁧 󱁨 󱁩 󱁪 󱁫 󱁬 󱁭 󱁮 󱁯
F1070   󱁰 󱁱 󱁲 󱁳 󱁴 󱁵 󱁶 󱁷 󱁸 󱁹 󱁺 󱁻 󱁼 󱁽 󱁾 󱁿
F1080   󱂀 󱂁 󱂂 󱂃 󱂄 󱂅 󱂆 󱂇 󱂈 󱂉 󱂊 󱂋 󱂌 󱂍 󱂎 󱂏
F1090   󱂐 󱂑 󱂒 󱂓 󱂔 󱂕 󱂖 󱂗 󱂘 󱂙 󱂚 󱂛 󱂜 󱂝 󱂞 󱂟
F10A0   󱂠 󱂡 󱂢 󱂣 󱂤 󱂥 󱂦 󱂧 󱂨 󱂩 󱂪 󱂫 󱂬 󱂭 󱂮 󱂯
F10B0   󱂰 󱂱 󱂲 󱂳 󱂴 󱂵 󱂶 󱂷 󱂸 󱂹 󱂺 󱂻 󱂼 󱂽 󱂾 󱂿
F10C0   󱃀 󱃁 󱃂 󱃃 󱃄 󱃅 󱃆 󱃇 󱃈 󱃉 󱃊 󱃋 󱃌 󱃍 󱃎 󱃏
F10D0   󱃐 󱃑 󱃒 󱃓 󱃔 󱃕 󱃖 󱃗 󱃘 󱃙 󱃚 󱃛 󱃜 󱃝 󱃞 󱃟
F10E0   󱃠 󱃡 󱃢 󱃣 󱃤 󱃥 󱃦 󱃧 󱃨 󱃩 󱃪 󱃫 󱃬 󱃭 󱃮 󱃯
F10F0   󱃰 󱃱 󱃲 󱃳 󱃴 󱃵 󱃶 󱃷 󱃸 󱃹 󱃺 󱃻 󱃼 󱃽 󱃾 󱃿
F1100   󱄀 󱄁 󱄂 󱄃 󱄄 󱄅 󱄆 󱄇 󱄈 󱄉 󱄊 󱄋 󱄌 󱄍 󱄎 󱄏
F1110   󱄐 󱄑 󱄒 󱄓 󱄔 󱄕 󱄖 󱄗 󱄘 󱄙 󱄚 󱄛 󱄜 󱄝 󱄞 󱄟
F1120   󱄠 󱄡 󱄢 󱄣 󱄤 󱄥 󱄦 󱄧 󱄨 󱄩 󱄪 󱄫 󱄬 󱄭 󱄮 󱄯
F1130   󱄰 󱄱 󱄲 󱄳 󱄴 󱄵 󱄶 󱄷 󱄸 󱄹 󱄺 󱄻 󱄼 󱄽 󱄾 󱄿
F1140   󱅀 󱅁 󱅂 󱅃 󱅄 󱅅 󱅆 󱅇 󱅈 󱅉 󱅊 󱅋 󱅌 󱅍 󱅎 󱅏
F1150   󱅐 󱅑 󱅒 󱅓 󱅔 󱅕 󱅖 󱅗 󱅘 󱅙 󱅚 󱅛 󱅜 󱅝 󱅞 󱅟
F1160   󱅠 󱅡 󱅢 󱅣 󱅤 󱅥 󱅦 󱅧 󱅨 󱅩 󱅪 󱅫 󱅬 󱅭 󱅮 󱅯
F1170   󱅰 󱅱 󱅲 󱅳 󱅴 󱅵 󱅶 󱅷 󱅸 󱅹 󱅺 󱅻 󱅼 󱅽 󱅾 󱅿
F1180   󱆀 󱆁 󱆂 󱆃 󱆄 󱆅 󱆆 󱆇 󱆈 󱆉 󱆊 󱆋 󱆌 󱆍 󱆎 󱆏
F1190   󱆐 󱆑 󱆒 󱆓 󱆔 󱆕 󱆖 󱆗 󱆘 󱆙 󱆚 󱆛 󱆜 󱆝 󱆞 󱆟
F11A0   󱆠 󱆡 󱆢 󱆣 󱆤 󱆥 󱆦 󱆧 󱆨 󱆩 󱆪 󱆫 󱆬 󱆭 󱆮 󱆯
F11B0   󱆰 󱆱 󱆲 󱆳 󱆴 󱆵 󱆶 󱆷 󱆸 󱆹 󱆺 󱆻 󱆼 󱆽 󱆾 󱆿
F11C0   󱇀 󱇁 󱇂 󱇃 󱇄 󱇅 󱇆 󱇇 󱇈 󱇉 󱇊 󱇋 󱇌 󱇍 󱇎 󱇏
F11D0   󱇐 󱇑 󱇒 󱇓 󱇔 󱇕 󱇖 󱇗 󱇘 󱇙 󱇚 󱇛 󱇜 󱇝 󱇞 󱇟
F11E0   󱇠 󱇡 󱇢 󱇣 󱇤 󱇥 󱇦 󱇧 󱇨 󱇩 󱇪 󱇫 󱇬 󱇭 󱇮 󱇯
F11F0   󱇰 󱇱 󱇲 󱇳 󱇴 󱇵 󱇶 󱇷 󱇸 󱇹 󱇺 󱇻 󱇼 󱇽 󱇾 󱇿
F1200   󱈀 󱈁 󱈂 󱈃 󱈄 󱈅 󱈆 󱈇 󱈈 󱈉 󱈊 󱈋 󱈌 󱈍 󱈎 󱈏
F1210   󱈐 󱈑 󱈒 󱈓 󱈔 󱈕 󱈖 󱈗 󱈘 󱈙 󱈚 󱈛 󱈜 󱈝 󱈞 󱈟
F1220   󱈠 󱈡 󱈢 󱈣 󱈤 󱈥 󱈦 󱈧 󱈨 󱈩 󱈪 󱈫 󱈬 󱈭 󱈮 󱈯
F1230   󱈰 󱈱 󱈲 󱈳 󱈴 󱈵 󱈶 󱈷 󱈸 󱈹 󱈺 󱈻 󱈼 󱈽 󱈾 󱈿
F1240   󱉀 󱉁 󱉂 󱉃 󱉄 󱉅 󱉆 󱉇 󱉈 󱉉 󱉊 󱉋 󱉌 󱉍 󱉎 󱉏
F1250   󱉐 󱉑 󱉒 󱉓 󱉔 󱉕 󱉖 󱉗 󱉘 󱉙 󱉚 󱉛 󱉜 󱉝 󱉞 󱉟
F1260   󱉠 󱉡 󱉢 󱉣 󱉤 󱉥 󱉦 󱉧 󱉨 󱉩 󱉪 󱉫 󱉬 󱉭 󱉮 󱉯
F1270   󱉰 󱉱 󱉲 󱉳 󱉴 󱉵 󱉶 󱉷 󱉸 󱉹 󱉺 󱉻 󱉼 󱉽 󱉾 󱉿
F1280   󱊀 󱊁 󱊂 󱊃 󱊄 󱊅 󱊆 󱊇 󱊈 󱊉 󱊊 󱊋 󱊌 󱊍 󱊎 󱊏
F1290   󱊐 󱊑 󱊒 󱊓 󱊔 󱊕 󱊖 󱊗 󱊘 󱊙 󱊚 󱊛 󱊜 󱊝 󱊞 󱊟
F12A0   󱊠 󱊡 󱊢 󱊣 󱊤 󱊥 󱊦 󱊧 󱊨 󱊩 󱊪 󱊫 󱊬 󱊭 󱊮 󱊯
F12B0   󱊰 󱊱 󱊲 󱊳 󱊴 󱊵 󱊶 󱊷 󱊸 󱊹 󱊺 󱊻 󱊼 󱊽 󱊾 󱊿
F12C0   󱋀 󱋁 󱋂 󱋃 󱋄 󱋅 󱋆 󱋇 󱋈 󱋉 󱋊 󱋋 󱋌 󱋍 󱋎 󱋏
F12D0   󱋐 󱋑 󱋒 󱋓 󱋔 󱋕 󱋖 󱋗 󱋘 󱋙 󱋚 󱋛 󱋜 󱋝 󱋞 󱋟
F12E0   󱋠 󱋡 󱋢 󱋣 󱋤 󱋥 󱋦 󱋧 󱋨 󱋩 󱋪 󱋫 󱋬 󱋭 󱋮 󱋯
F12F0   󱋰 󱋱 󱋲 󱋳 󱋴 󱋵 󱋶 󱋷 󱋸 󱋹 󱋺 󱋻 󱋼 󱋽 󱋾 󱋿
F1300   󱌀 󱌁 󱌂 󱌃 󱌄 󱌅 󱌆 󱌇 󱌈 󱌉 󱌊 󱌋 󱌌 󱌍 󱌎 󱌏
F1310   󱌐 󱌑 󱌒 󱌓 󱌔 󱌕 󱌖 󱌗 󱌘 󱌙 󱌚 󱌛 󱌜 󱌝 󱌞 󱌟
F1320   󱌠 󱌡 󱌢 󱌣 󱌤 󱌥 󱌦 󱌧 󱌨 󱌩 󱌪 󱌫 󱌬 󱌭 󱌮 󱌯
F1330   󱌰 󱌱 󱌲 󱌳 󱌴 󱌵 󱌶 󱌷 󱌸 󱌹 󱌺 󱌻 󱌼 󱌽 󱌾 󱌿
F1340   󱍀 󱍁 󱍂 󱍃 󱍄 󱍅 󱍆 󱍇 󱍈 󱍉 󱍊 󱍋 󱍌 󱍍 󱍎 󱍏
F1350   󱍐 󱍑 󱍒 󱍓 󱍔 󱍕 󱍖 󱍗 󱍘 󱍙 󱍚 󱍛 󱍜 󱍝 󱍞 󱍟
F1360   󱍠 󱍡 󱍢 󱍣 󱍤 󱍥 󱍦 󱍧 󱍨 󱍩 󱍪 󱍫 󱍬 󱍭 󱍮 󱍯
F1370   󱍰 󱍱 󱍲 󱍳 󱍴 󱍵 󱍶 󱍷 󱍸 󱍹 󱍺 󱍻 󱍼 󱍽 󱍾 󱍿
F1380   󱎀 󱎁 󱎂 󱎃 󱎄 󱎅 󱎆 󱎇 󱎈 󱎉 󱎊 󱎋 󱎌 󱎍 󱎎 󱎏
F1390   󱎐 󱎑 󱎒 󱎓 󱎔 󱎕 󱎖 󱎗 󱎘 󱎙 󱎚 󱎛 󱎜 󱎝 󱎞 󱎟
F13A0   󱎠 󱎡 󱎢 󱎣 󱎤 󱎥 󱎦 󱎧 󱎨 󱎩 󱎪 󱎫 󱎬 󱎭 󱎮 󱎯
F13B0   󱎰 󱎱 󱎲 󱎳 󱎴 󱎵 󱎶 󱎷 󱎸 󱎹 󱎺 󱎻 󱎼 󱎽 󱎾 󱎿
F13C0   󱏀 󱏁 󱏂 󱏃 󱏄 󱏅 󱏆 󱏇 󱏈 󱏉 󱏊 󱏋 󱏌 󱏍 󱏎 󱏏
F13D0   󱏐 󱏑 󱏒 󱏓 󱏔 󱏕 󱏖 󱏗 󱏘 󱏙 󱏚 󱏛 󱏜 󱏝 󱏞 󱏟
F13E0   󱏠 󱏡 󱏢 󱏣 󱏤 󱏥 󱏦 󱏧 󱏨 󱏩 󱏪 󱏫 󱏬 󱏭 󱏮 󱏯
F13F0   󱏰 󱏱 󱏲 󱏳 󱏴 󱏵 󱏶 󱏷 󱏸 󱏹 󱏺 󱏻 󱏼 󱏽 󱏾 󱏿

*** F1400–F17FF
F1400   󱐀 󱐁 󱐂 󱐃 󱐄 󱐅 󱐆 󱐇 󱐈 󱐉 󱐊 󱐋 󱐌 󱐍 󱐎 󱐏
F1410   󱐐 󱐑 󱐒 󱐓 󱐔 󱐕 󱐖 󱐗 󱐘 󱐙 󱐚 󱐛 󱐜 󱐝 󱐞 󱐟
F1420   󱐠 󱐡 󱐢 󱐣 󱐤 󱐥 󱐦 󱐧 󱐨 󱐩 󱐪 󱐫 󱐬 󱐭 󱐮 󱐯
F1430   󱐰 󱐱 󱐲 󱐳 󱐴 󱐵 󱐶 󱐷 󱐸 󱐹 󱐺 󱐻 󱐼 󱐽 󱐾 󱐿
F1440   󱑀 󱑁 󱑂 󱑃 󱑄 󱑅 󱑆 󱑇 󱑈 󱑉 󱑊 󱑋 󱑌 󱑍 󱑎 󱑏
F1450   󱑐 󱑑 󱑒 󱑓 󱑔 󱑕 󱑖 󱑗 󱑘 󱑙 󱑚 󱑛 󱑜 󱑝 󱑞 󱑟
F1460   󱑠 󱑡 󱑢 󱑣 󱑤 󱑥 󱑦 󱑧 󱑨 󱑩 󱑪 󱑫 󱑬 󱑭 󱑮 󱑯
F1470   󱑰 󱑱 󱑲 󱑳 󱑴 󱑵 󱑶 󱑷 󱑸 󱑹 󱑺 󱑻 󱑼 󱑽 󱑾 󱑿
F1480   󱒀 󱒁 󱒂 󱒃 󱒄 󱒅 󱒆 󱒇 󱒈 󱒉 󱒊 󱒋 󱒌 󱒍 󱒎 󱒏
F1490   󱒐 󱒑 󱒒 󱒓 󱒔 󱒕 󱒖 󱒗 󱒘 󱒙 󱒚 󱒛 󱒜 󱒝 󱒞 󱒟
F14A0   󱒠 󱒡 󱒢 󱒣 󱒤 󱒥 󱒦 󱒧 󱒨 󱒩 󱒪 󱒫 󱒬 󱒭 󱒮 󱒯
F14B0   󱒰 󱒱 󱒲 󱒳 󱒴 󱒵 󱒶 󱒷 󱒸 󱒹 󱒺 󱒻 󱒼 󱒽 󱒾 󱒿
F14C0   󱓀 󱓁 󱓂 󱓃 󱓄 󱓅 󱓆 󱓇 󱓈 󱓉 󱓊 󱓋 󱓌 󱓍 󱓎 󱓏
F14D0   󱓐 󱓑 󱓒 󱓓 󱓔 󱓕 󱓖 󱓗 󱓘 󱓙 󱓚 󱓛 󱓜 󱓝 󱓞 󱓟
F14E0   󱓠 󱓡 󱓢 󱓣 󱓤 󱓥 󱓦 󱓧 󱓨 󱓩 󱓪 󱓫 󱓬 󱓭 󱓮 󱓯
F14F0   󱓰 󱓱 󱓲 󱓳 󱓴 󱓵 󱓶 󱓷 󱓸 󱓹 󱓺 󱓻 󱓼 󱓽 󱓾 󱓿
F1500   󱔀 󱔁 󱔂 󱔃 󱔄 󱔅 󱔆 󱔇 󱔈 󱔉 󱔊 󱔋 󱔌 󱔍 󱔎 󱔏
F1510   󱔐 󱔑 󱔒 󱔓 󱔔 󱔕 󱔖 󱔗 󱔘 󱔙 󱔚 󱔛 󱔜 󱔝 󱔞 󱔟
F1520   󱔠 󱔡 󱔢 󱔣 󱔤 󱔥 󱔦 󱔧 󱔨 󱔩 󱔪 󱔫 󱔬 󱔭 󱔮 󱔯
F1530   󱔰 󱔱 󱔲 󱔳 󱔴 󱔵 󱔶 󱔷 󱔸 󱔹 󱔺 󱔻 󱔼 󱔽 󱔾 󱔿
F1540   󱕀 󱕁 󱕂 󱕃 󱕄 󱕅 󱕆 󱕇 󱕈 󱕉 󱕊 󱕋 󱕌 󱕍 󱕎 󱕏
F1550   󱕐 󱕑 󱕒 󱕓 󱕔 󱕕 󱕖 󱕗 󱕘 󱕙 󱕚 󱕛 󱕜 󱕝 󱕞 󱕟
F1560   󱕠 󱕡 󱕢 󱕣 󱕤 󱕥 󱕦 󱕧 󱕨 󱕩 󱕪 󱕫 󱕬 󱕭 󱕮 󱕯
F1570   󱕰 󱕱 󱕲 󱕳 󱕴 󱕵 󱕶 󱕷 󱕸 󱕹 󱕺 󱕻 󱕼 󱕽 󱕾 󱕿
F1580   󱖀 󱖁 󱖂 󱖃 󱖄 󱖅 󱖆 󱖇 󱖈 󱖉 󱖊 󱖋 󱖌 󱖍 󱖎 󱖏
F1590   󱖐 󱖑 󱖒 󱖓 󱖔 󱖕 󱖖 󱖗 󱖘 󱖙 󱖚 󱖛 󱖜 󱖝 󱖞 󱖟
F15A0   󱖠 󱖡 󱖢 󱖣 󱖤 󱖥 󱖦 󱖧 󱖨 󱖩 󱖪 󱖫 󱖬 󱖭 󱖮 󱖯
F15B0   󱖰 󱖱 󱖲 󱖳 󱖴 󱖵 󱖶 󱖷 󱖸 󱖹 󱖺 󱖻 󱖼 󱖽 󱖾 󱖿
F15C0   󱗀 󱗁 󱗂 󱗃 󱗄 󱗅 󱗆 󱗇 󱗈 󱗉 󱗊 󱗋 󱗌 󱗍 󱗎 󱗏
F15D0   󱗐 󱗑 󱗒 󱗓 󱗔 󱗕 󱗖 󱗗 󱗘 󱗙 󱗚 󱗛 󱗜 󱗝 󱗞 󱗟
F15E0   󱗠 󱗡 󱗢 󱗣 󱗤 󱗥 󱗦 󱗧 󱗨 󱗩 󱗪 󱗫 󱗬 󱗭 󱗮 󱗯
F15F0   󱗰 󱗱 󱗲 󱗳 󱗴 󱗵 󱗶 󱗷 󱗸 󱗹 󱗺 󱗻 󱗼 󱗽 󱗾 󱗿
F1600   󱘀 󱘁 󱘂 󱘃 󱘄 󱘅 󱘆 󱘇 󱘈 󱘉 󱘊 󱘋 󱘌 󱘍 󱘎 󱘏
F1610   󱘐 󱘑 󱘒 󱘓 󱘔 󱘕 󱘖 󱘗 󱘘 󱘙 󱘚 󱘛 󱘜 󱘝 󱘞 󱘟
F1620   󱘠 󱘡 󱘢 󱘣 󱘤 󱘥 󱘦 󱘧 󱘨 󱘩 󱘪 󱘫 󱘬 󱘭 󱘮 󱘯
F1630   󱘰 󱘱 󱘲 󱘳 󱘴 󱘵 󱘶 󱘷 󱘸 󱘹 󱘺 󱘻 󱘼 󱘽 󱘾 󱘿
F1640   󱙀 󱙁 󱙂 󱙃 󱙄 󱙅 󱙆 󱙇 󱙈 󱙉 󱙊 󱙋 󱙌 󱙍 󱙎 󱙏
F1650   󱙐 󱙑 󱙒 󱙓 󱙔 󱙕 󱙖 󱙗 󱙘 󱙙 󱙚 󱙛 󱙜 󱙝 󱙞 󱙟
F1660   󱙠 󱙡 󱙢 󱙣 󱙤 󱙥 󱙦 󱙧 󱙨 󱙩 󱙪 󱙫 󱙬 󱙭 󱙮 󱙯
F1670   󱙰 󱙱 󱙲 󱙳 󱙴 󱙵 󱙶 󱙷 󱙸 󱙹 󱙺 󱙻 󱙼 󱙽 󱙾 󱙿
F1680   󱚀 󱚁 󱚂 󱚃 󱚄 󱚅 󱚆 󱚇 󱚈 󱚉 󱚊 󱚋 󱚌 󱚍 󱚎 󱚏
F1690   󱚐 󱚑 󱚒 󱚓 󱚔 󱚕 󱚖 󱚗 󱚘 󱚙 󱚚 󱚛 󱚜 󱚝 󱚞 󱚟
F16A0   󱚠 󱚡 󱚢 󱚣 󱚤 󱚥 󱚦 󱚧 󱚨 󱚩 󱚪 󱚫 󱚬 󱚭 󱚮 󱚯
F16B0   󱚰 󱚱 󱚲 󱚳 󱚴 󱚵 󱚶 󱚷 󱚸 󱚹 󱚺 󱚻 󱚼 󱚽 󱚾 󱚿
F16C0   󱛀 󱛁 󱛂 󱛃 󱛄 󱛅 󱛆 󱛇 󱛈 󱛉 󱛊 󱛋 󱛌 󱛍 󱛎 󱛏
F16D0   󱛐 󱛑 󱛒 󱛓 󱛔 󱛕 󱛖 󱛗 󱛘 󱛙 󱛚 󱛛 󱛜 󱛝 󱛞 󱛟
F16E0   󱛠 󱛡 󱛢 󱛣 󱛤 󱛥 󱛦 󱛧 󱛨 󱛩 󱛪 󱛫 󱛬 󱛭 󱛮 󱛯
F16F0   󱛰 󱛱 󱛲 󱛳 󱛴 󱛵 󱛶 󱛷 󱛸 󱛹 󱛺 󱛻 󱛼 󱛽 󱛾 󱛿
F1700   󱜀 󱜁 󱜂 󱜃 󱜄 󱜅 󱜆 󱜇 󱜈 󱜉 󱜊 󱜋 󱜌 󱜍 󱜎 󱜏
F1710   󱜐 󱜑 󱜒 󱜓 󱜔 󱜕 󱜖 󱜗 󱜘 󱜙 󱜚 󱜛 󱜜 󱜝 󱜞 󱜟
F1720   󱜠 󱜡 󱜢 󱜣 󱜤 󱜥 󱜦 󱜧 󱜨 󱜩 󱜪 󱜫 󱜬 󱜭 󱜮 󱜯
F1730   󱜰 󱜱 󱜲 󱜳 󱜴 󱜵 󱜶 󱜷 󱜸 󱜹 󱜺 󱜻 󱜼 󱜽 󱜾 󱜿
F1740   󱝀 󱝁 󱝂 󱝃 󱝄 󱝅 󱝆 󱝇 󱝈 󱝉 󱝊 󱝋 󱝌 󱝍 󱝎 󱝏
F1750   󱝐 󱝑 󱝒 󱝓 󱝔 󱝕 󱝖 󱝗 󱝘 󱝙 󱝚 󱝛 󱝜 󱝝 󱝞 󱝟
F1760   󱝠 󱝡 󱝢 󱝣 󱝤 󱝥 󱝦 󱝧 󱝨 󱝩 󱝪 󱝫 󱝬 󱝭 󱝮 󱝯
F1770   󱝰 󱝱 󱝲 󱝳 󱝴 󱝵 󱝶 󱝷 󱝸 󱝹 󱝺 󱝻 󱝼 󱝽 󱝾 󱝿
F1780   󱞀 󱞁 󱞂 󱞃 󱞄 󱞅 󱞆 󱞇 󱞈 󱞉 󱞊 󱞋 󱞌 󱞍 󱞎 󱞏
F1790   󱞐 󱞑 󱞒 󱞓 󱞔 󱞕 󱞖 󱞗 󱞘 󱞙 󱞚 󱞛 󱞜 󱞝 󱞞 󱞟
F17A0   󱞠 󱞡 󱞢 󱞣 󱞤 󱞥 󱞦 󱞧 󱞨 󱞩 󱞪 󱞫 󱞬 󱞭 󱞮 󱞯
F17B0   󱞰 󱞱 󱞲 󱞳 󱞴 󱞵 󱞶 󱞷 󱞸 󱞹 󱞺 󱞻 󱞼 󱞽 󱞾 󱞿
F17C0   󱟀 󱟁 󱟂 󱟃 󱟄 󱟅 󱟆 󱟇 󱟈 󱟉 󱟊 󱟋 󱟌 󱟍 󱟎 󱟏
F17D0   󱟐 󱟑 󱟒 󱟓 󱟔 󱟕 󱟖 󱟗 󱟘 󱟙 󱟚 󱟛 󱟜 󱟝 󱟞 󱟟
F17E0   󱟠 󱟡 󱟢 󱟣 󱟤 󱟥 󱟦 󱟧 󱟨 󱟩 󱟪 󱟫 󱟬 󱟭 󱟮 󱟯
F17F0   󱟰 󱟱 󱟲 󱟳 󱟴 󱟵 󱟶 󱟷 󱟸 󱟹 󱟺 󱟻 󱟼 󱟽 󱟾 󱟿

*** F1800–F1AF0
F1800   󱠀 󱠁 󱠂 󱠃 󱠄 󱠅 󱠆 󱠇 󱠈 󱠉 󱠊 󱠋 󱠌 󱠍 󱠎 󱠏
F1810   󱠐 󱠑 󱠒 󱠓 󱠔 󱠕 󱠖 󱠗 󱠘 󱠙 󱠚 󱠛 󱠜 󱠝 󱠞 󱠟
F1820   󱠠 󱠡 󱠢 󱠣 󱠤 󱠥 󱠦 󱠧 󱠨 󱠩 󱠪 󱠫 󱠬 󱠭 󱠮 󱠯
F1830   󱠰 󱠱 󱠲 󱠳 󱠴 󱠵 󱠶 󱠷 󱠸 󱠹 󱠺 󱠻 󱠼 󱠽 󱠾 󱠿
F1840   󱡀 󱡁 󱡂 󱡃 󱡄 󱡅 󱡆 󱡇 󱡈 󱡉 󱡊 󱡋 󱡌 󱡍 󱡎 󱡏
F1850   󱡐 󱡑 󱡒 󱡓 󱡔 󱡕 󱡖 󱡗 󱡘 󱡙 󱡚 󱡛 󱡜 󱡝 󱡞 󱡟
F1860   󱡠 󱡡 󱡢 󱡣 󱡤 󱡥 󱡦 󱡧 󱡨 󱡩 󱡪 󱡫 󱡬 󱡭 󱡮 󱡯
F1870   󱡰 󱡱 󱡲 󱡳 󱡴 󱡵 󱡶 󱡷 󱡸 󱡹 󱡺 󱡻 󱡼 󱡽 󱡾 󱡿
F1880   󱢀 󱢁 󱢂 󱢃 󱢄 󱢅 󱢆 󱢇 󱢈 󱢉 󱢊 󱢋 󱢌 󱢍 󱢎 󱢏
F1890   󱢐 󱢑 󱢒 󱢓 󱢔 󱢕 󱢖 󱢗 󱢘 󱢙 󱢚 󱢛 󱢜 󱢝 󱢞 󱢟
F18A0   󱢠 󱢡 󱢢 󱢣 󱢤 󱢥 󱢦 󱢧 󱢨 󱢩 󱢪 󱢫 󱢬 󱢭 󱢮 󱢯
F18B0   󱢰 󱢱 󱢲 󱢳 󱢴 󱢵 󱢶 󱢷 󱢸 󱢹 󱢺 󱢻 󱢼 󱢽 󱢾 󱢿
F18C0   󱣀 󱣁 󱣂 󱣃 󱣄 󱣅 󱣆 󱣇 󱣈 󱣉 󱣊 󱣋 󱣌 󱣍 󱣎 󱣏
F18D0   󱣐 󱣑 󱣒 󱣓 󱣔 󱣕 󱣖 󱣗 󱣘 󱣙 󱣚 󱣛 󱣜 󱣝 󱣞 󱣟
F18E0   󱣠 󱣡 󱣢 󱣣 󱣤 󱣥 󱣦 󱣧 󱣨 󱣩 󱣪 󱣫 󱣬 󱣭 󱣮 󱣯
F18F0   󱣰 󱣱 󱣲 󱣳 󱣴 󱣵 󱣶 󱣷 󱣸 󱣹 󱣺 󱣻 󱣼 󱣽 󱣾 󱣿
F1900   󱤀 󱤁 󱤂 󱤃 󱤄 󱤅 󱤆 󱤇 󱤈 󱤉 󱤊 󱤋 󱤌 󱤍 󱤎 󱤏
F1910   󱤐 󱤑 󱤒 󱤓 󱤔 󱤕 󱤖 󱤗 󱤘 󱤙 󱤚 󱤛 󱤜 󱤝 󱤞 󱤟
F1920   󱤠 󱤡 󱤢 󱤣 󱤤 󱤥 󱤦 󱤧 󱤨 󱤩 󱤪 󱤫 󱤬 󱤭 󱤮 󱤯
F1930   󱤰 󱤱 󱤲 󱤳 󱤴 󱤵 󱤶 󱤷 󱤸 󱤹 󱤺 󱤻 󱤼 󱤽 󱤾 󱤿
F1940   󱥀 󱥁 󱥂 󱥃 󱥄 󱥅 󱥆 󱥇 󱥈 󱥉 󱥊 󱥋 󱥌 󱥍 󱥎 󱥏
F1950   󱥐 󱥑 󱥒 󱥓 󱥔 󱥕 󱥖 󱥗 󱥘 󱥙 󱥚 󱥛 󱥜 󱥝 󱥞 󱥟
F1960   󱥠 󱥡 󱥢 󱥣 󱥤 󱥥 󱥦 󱥧 󱥨 󱥩 󱥪 󱥫 󱥬 󱥭 󱥮 󱥯
F1970   󱥰 󱥱 󱥲 󱥳 󱥴 󱥵 󱥶 󱥷 󱥸 󱥹 󱥺 󱥻 󱥼 󱥽 󱥾 󱥿
F1980   󱦀 󱦁 󱦂 󱦃 󱦄 󱦅 󱦆 󱦇 󱦈 󱦉 󱦊 󱦋 󱦌 󱦍 󱦎 󱦏
F1990   󱦐 󱦑 󱦒 󱦓 󱦔 󱦕 󱦖 󱦗 󱦘 󱦙 󱦚 󱦛 󱦜 󱦝 󱦞 󱦟
F19A0   󱦠 󱦡 󱦢 󱦣 󱦤 󱦥 󱦦 󱦧 󱦨 󱦩 󱦪 󱦫 󱦬 󱦭 󱦮 󱦯
F19B0   󱦰 󱦱 󱦲 󱦳 󱦴 󱦵 󱦶 󱦷 󱦸 󱦹 󱦺 󱦻 󱦼 󱦽 󱦾 󱦿
F19C0   󱧀 󱧁 󱧂 󱧃 󱧄 󱧅 󱧆 󱧇 󱧈 󱧉 󱧊 󱧋 󱧌 󱧍 󱧎 󱧏
F19D0   󱧐 󱧑 󱧒 󱧓 󱧔 󱧕 󱧖 󱧗 󱧘 󱧙 󱧚 󱧛 󱧜 󱧝 󱧞 󱧟
F19E0   󱧠 󱧡 󱧢 󱧣 󱧤 󱧥 󱧦 󱧧 󱧨 󱧩 󱧪 󱧫 󱧬 󱧭 󱧮 󱧯
F19F0   󱧰 󱧱 󱧲 󱧳 󱧴 󱧵 󱧶 󱧷 󱧸 󱧹 󱧺 󱧻 󱧼 󱧽 󱧾 󱧿
F1A00   󱨀 󱨁 󱨂 󱨃 󱨄 󱨅 󱨆 󱨇 󱨈 󱨉 󱨊 󱨋 󱨌 󱨍 󱨎 󱨏
F1A10   󱨐 󱨑 󱨒 󱨓 󱨔 󱨕 󱨖 󱨗 󱨘 󱨙 󱨚 󱨛 󱨜 󱨝 󱨞 󱨟
F1A20   󱨠 󱨡 󱨢 󱨣 󱨤 󱨥 󱨦 󱨧 󱨨 󱨩 󱨪 󱨫 󱨬 󱨭 󱨮 󱨯
F1A30   󱨰 󱨱 󱨲 󱨳 󱨴 󱨵 󱨶 󱨷 󱨸 󱨹 󱨺 󱨻 󱨼 󱨽 󱨾 󱨿
F1A40   󱩀 󱩁 󱩂 󱩃 󱩄 󱩅 󱩆 󱩇 󱩈 󱩉 󱩊 󱩋 󱩌 󱩍 󱩎 󱩏
F1A50   󱩐 󱩑 󱩒 󱩓 󱩔 󱩕 󱩖 󱩗 󱩘 󱩙 󱩚 󱩛 󱩜 󱩝 󱩞 󱩟
F1A60   󱩠 󱩡 󱩢 󱩣 󱩤 󱩥 󱩦 󱩧 󱩨 󱩩 󱩪 󱩫 󱩬 󱩭 󱩮 󱩯
F1A70   󱩰 󱩱 󱩲 󱩳 󱩴 󱩵 󱩶 󱩷 󱩸 󱩹 󱩺 󱩻 󱩼 󱩽 󱩾 󱩿
F1A80   󱪀 󱪁 󱪂 󱪃 󱪄 󱪅 󱪆 󱪇 󱪈 󱪉 󱪊 󱪋 󱪌 󱪍 󱪎 󱪏
F1A90   󱪐 󱪑 󱪒 󱪓 󱪔 󱪕 󱪖 󱪗 󱪘 󱪙 󱪚 󱪛 󱪜 󱪝 󱪞 󱪟
F1AA0   󱪠 󱪡 󱪢 󱪣 󱪤 󱪥 󱪦 󱪧 󱪨 󱪩 󱪪 󱪫 󱪬 󱪭 󱪮 󱪯
F1AB0   󱪰 󱪱 󱪲 󱪳 󱪴 󱪵 󱪶 󱪷 󱪸 󱪹 󱪺 󱪻 󱪼 󱪽 󱪾 󱪿
F1AC0   󱫀 󱫁 󱫂 󱫃 󱫄 󱫅 󱫆 󱫇 󱫈 󱫉 󱫊 󱫋 󱫌 󱫍 󱫎 󱫏
F1AD0   󱫐 󱫑 󱫒 󱫓 󱫔 󱫕 󱫖 󱫗 󱫘 󱫙 󱫚 󱫛 󱫜 󱫝 󱫞 󱫟
F1AE0   󱫠 󱫡 󱫢 󱫣 󱫤 󱫥 󱫦 󱫧 󱫨 󱫩 󱫪 󱫫 󱫬 󱫭 󱫮 󱫯
F1AF0   󱫰 · · · · · · · · · · · · · · ·
